// AUTO-GENERATED by scripts/generate-supervisor-templates.mjs
// DO NOT EDIT DIRECTLY — edit docs/supervisor/plans/*.yml instead,
// then run: node scripts/generate-supervisor-templates.mjs
//
// Generated: 2026-05-06T20:10:25.255Z
// Source files: db-migration-gap-fix.yml, deps-bump-minor-patch.yml, docs-naming-convention.yml, feat-ci-workflow.yml, fix-analytics-event-whitelist.yml, fix-billing-portal-400.yml, fix-ci-package-auth.yml, fix-csp-hash.yml, fix-mobile-layout.yml, fix-stripe-price-id.yml, governance-hardening.yml, migration-drift-fix.yml, package-version-migration.yml, reusable-workflow-rollout.yml, security-codeql-fix.yml, sentry-stripe-error-triage.yml, sentry-triage-new-issue.yml, syn-package-migration.yml, user-account-suspend.yml, ux-regression-triage.yml, worker-health-degraded.yml, wrangler-config-drift-fix.yml

import type { Template } from './load';

export const GENERATED_TEMPLATES: Template[] = [
  {
    "id": "db-migration-gap-fix",
    "tier": "yellow",
    "description": "",
    "trigger_keywords": [
      "bug",
      "migration",
      "gap",
      "fix"
    ],
    "triggers": {
      "labels_any_of": [
        "bug"
      ],
      "title_pattern": "^(MIGRATION:|DatabaseError|column .* does not exist)",
      "body_patterns": [
        "(sentry\\.io/|DatabaseError|does not exist)"
      ]
    },
    "steps": [
      {
        "tool": "sentry.getIssue",
        "slots": {
          "issue_id": "$slots.sentry_issue_id"
        },
        "side_effects": "none"
      },
      {
        "tool": "github.readFile",
        "slots": {
          "path": "workers/src/db/migrations/",
          "ref": "main",
          "grep": "$slots.column_or_relation"
        },
        "side_effects": "none"
      },
      {
        "tool": "github.readFile",
        "slots": {
          "path": "workers/src/db/migrations/",
          "ref": "main",
          "grep": "$slots.table_name"
        },
        "side_effects": "none"
      },
      {
        "tool": "github.comment",
        "slots": {
          "body": "Supervisor runbook: apply migrations that introduce `$slots.table_name.$slots.column_or_relation` on prod. Migration authored in repo (see $s2.matches, $s3.matches) but not applied in prod database. Human action required: run `psql` against prod replica of the affected worker DB and apply migrations N..M in order. Sentry: $slots.sentry_issue_id. If no matching migration is found in $s2/$s3, reclassify this issue to tier:red (migration authoring needed)."
        },
        "side_effects": "none"
      },
      {
        "tool": "github.addLabel",
        "slots": {
          "label": "needs-human:db-migration"
        },
        "side_effects": "none"
      }
    ]
  },
  {
    "id": "deps-bump-minor-patch",
    "tier": "green",
    "description": "",
    "trigger_keywords": [
      "dependencies",
      "deps",
      "bump",
      "minor",
      "patch"
    ],
    "triggers": {
      "labels_any_of": [
        "dependencies"
      ],
      "title_pattern": "^(chore\\(deps\\):|Bump)",
      "body_patterns": [
        "(?i)bumps?\\s+\\[?[@A-Za-z0-9._/-]+\\]?\\s+from\\s+v?\\d+\\.\\d+\\.\\d+\\s+to\\s+v?\\d+\\.\\d+\\.\\d+"
      ]
    },
    "steps": [
      {
        "tool": "github.readFile",
        "slots": {
          "repo": "$slots.repo_name",
          "path": "package.json"
        },
        "side_effects": "none"
      },
      {
        "tool": "github.readFile",
        "slots": {
          "repo": "$slots.repo_name",
          "path": "package-lock.json"
        },
        "side_effects": "none"
      },
      {
        "tool": "github.addLabel",
        "slots": {
          "repo": "$slots.repo_name",
          "label": "auto-merge-green"
        },
        "side_effects": "none"
      },
      {
        "tool": "github.comment",
        "slots": {
          "repo": "$slots.repo_name",
          "body": "Green-tier supervisor approving $slots.bump_kind bump of $slots.package_name from $slots.from_version to $slots.to_version. CI is green and no security advisory blocks."
        },
        "side_effects": "none"
      },
      {
        "tool": "github.mergePR",
        "slots": {
          "repo": "$slots.repo_name",
          "merge_method": "squash"
        },
        "side_effects": "none"
      }
    ]
  },
  {
    "id": "docs-naming-convention",
    "tier": "green",
    "description": "",
    "trigger_keywords": [
      "docs",
      "documentation",
      "hardening",
      "naming",
      "convention"
    ],
    "triggers": {
      "labels_any_of": [
        "docs",
        "documentation",
        "hardening"
      ],
      "title_pattern": "^docs[(:]",
      "body_patterns": [
        "(?is)path\\s*[:=]\\s*(docs|documents)/",
        "(?is)(content|body)\\s*[:=]"
      ]
    },
    "steps": [
      {
        "tool": "github.readFile",
        "slots": {
          "path": "$slots.parent_dir",
          "ref": "main"
        },
        "side_effects": "none"
      },
      {
        "tool": "github.readFile",
        "slots": {
          "path": "$slots.target_path",
          "ref": "main",
          "allow_missing": true
        },
        "side_effects": "none"
      },
      {
        "tool": "github.openPR",
        "slots": {
          "branch": "$slots.branch_name",
          "base": "main",
          "title": "$slots.commit_message",
          "commit_message": "$slots.commit_message",
          "files": [
            {
              "path": "$slots.target_path",
              "content": "$slots.doc_body"
            }
          ],
          "body": "Auto-drafted by supervisor for cluster `docs-naming-convention`.\nScope: $slots.scope\nTarget: $slots.target_path\nSource issue: see linked issue.\n",
          "labels": [
            "docs",
            "supervisor",
            "tier-green"
          ]
        },
        "side_effects": "none"
      },
      {
        "tool": "github.comment",
        "slots": {
          "pr": "$s3.number",
          "body": "Supervisor opened this docs PR from the linked issue. CI runs docs-lint + credential-scrub only; no code paths touched."
        },
        "side_effects": "none"
      }
    ]
  },
  {
    "id": "feat-ci-workflow",
    "tier": "yellow",
    "description": "",
    "trigger_keywords": [
      "engineering",
      "hardening",
      "enhancement",
      "feat",
      "workflow"
    ],
    "triggers": {
      "labels_any_of": [
        "engineering",
        "hardening",
        "enhancement"
      ],
      "title_pattern": "(feat\\(ci\\)|feat\\(triage\\)|feat\\(review\\)|feat\\(reliability\\)|feat\\(process\\)|chore\\(ci\\)|chore\\(process\\)|chore\\(governance\\))",
      "body_patterns": [
        "(github actions|workflow|\\.github/workflows|ci check|path\\.based|required\\.check)"
      ]
    },
    "steps": [
      {
        "tool": "github.readFile",
        "slots": {
          "repo": "factory",
          "path": ".github/workflows/COORDINATION.md",
          "ref": "main"
        },
        "side_effects": "none"
      },
      {
        "tool": "github.comment",
        "slots": {
          "issue_ref": "$triggers.issue_number",
          "body": "Supervisor plan for `$slots.workflow_name`\n\n**Trigger events:** `$slots.trigger_events`\n**Description:** $slots.description\n\nDrafting workflow YAML following Factory conventions. Will open a draft PR.\n\n@adrper79-dot — React ✅ to proceed, or comment with changes needed."
        },
        "side_effects": "none"
      },
      {
        "tool": "github.openPR",
        "slots": {
          "repo": "factory",
          "base": "main",
          "head": "supervisor/ci-$slots.workflow_name",
          "title": "feat(ci): add $slots.workflow_name workflow",
          "body": "Closes #$triggers.issue_number\n\nAdds `.github/workflows/$slots.workflow_name.yml` implementing: $slots.description\n\nFollows Factory App token pattern and COORDINATION.md conventions.\n\nGenerated by supervisor. Human review required before merge.",
          "draft": true
        },
        "side_effects": "none"
      }
    ]
  },
  {
    "id": "fix-analytics-event-whitelist",
    "tier": "yellow",
    "description": "Analytics endpoint returns 400 because a client event name is missing from the server-side PUBLIC_SHELL_EVENT_NAMES whitelist.",
    "trigger_keywords": [
      "analytics",
      "whitelist",
      "shell-event",
      "400",
      "event",
      "unsupported"
    ],
    "triggers": {
      "labels_any_of": [
        "bug"
      ],
      "title_pattern": "(analytics.*400|shell.event.*400|400.*shell.event|event.*whitelist|whitelist.*event|Unsupported shell event)",
      "body_patterns": [
        "(PUBLIC_SHELL_EVENT_NAMES|shell.event.*400|Unsupported shell event|analytics.*handler.*400)"
      ]
    },
    "steps": [
      {
        "tool": "github.readFile",
        "slots": {
          "repo": "Latimer-Woods-Tech/$slots.affected_app",
          "path": "$slots.handler_file",
          "ref": "main"
        },
        "side_effects": "none"
      },
      {
        "tool": "github.comment",
        "slots": {
          "body": "**Supervisor diagnosis — analytics whitelist gap in `$slots.affected_app`**\n\nMissing event name(s): `$slots.missing_event_names`\nHandler file: `$slots.handler_file`\n\nCurrent whitelist excerpt (from $s1):\n```\n$s1.excerpt\n```\n\n**Fix:** Add `$slots.missing_event_names` to the `PUBLIC_SHELL_EVENT_NAMES` set in `$slots.handler_file`. No client changes required — the client payload shape is correct.\n\nA draft PR will be opened to add the missing event names.\n\n_Run ID: $RUN_ID_\n"
        },
        "side_effects": "none"
      },
      {
        "tool": "github.openPR",
        "slots": {
          "repo": "Latimer-Woods-Tech/$slots.affected_app",
          "base": "main",
          "head": "supervisor/analytics-whitelist-$slots.affected_app",
          "title": "fix(analytics): add missing event names to PUBLIC_SHELL_EVENT_NAMES",
          "body": "Closes #$triggers.issue_number\n\n**Root cause:** `POST /api/analytics/shell-event` returned HTTP 400 for event name(s) `$slots.missing_event_names` because they are absent from `PUBLIC_SHELL_EVENT_NAMES` in `$slots.handler_file`.\n\n**Fix:** Adds the missing event name(s) to the whitelist. No client changes needed.\n\nDiagnosis: see issue comment $s2.comment_url\n\nThis PR was generated by the supervisor. Human review required before merge.\n",
          "draft": true
        },
        "side_effects": "none"
      }
    ]
  },
  {
    "id": "fix-billing-portal-400",
    "tier": "red",
    "description": "Billing portal endpoint returns HTTP 400, typically because stripe_customer_id is null for a paid user whose Stripe webhook was missed or raced.",
    "trigger_keywords": [
      "billing",
      "portal",
      "400",
      "stripe",
      "customer",
      "subscription",
      "manage"
    ],
    "triggers": {
      "labels_any_of": [
        "bug",
        "area:billing"
      ],
      "title_pattern": "(billing.*portal.*400|portal.*400|Manage Subscription.*broken|billing.*400|portal.*error)",
      "body_patterns": [
        "(billing/portal|handlePortal|stripe_customer_id.*null|portal.*400|Manage Subscription)"
      ]
    },
    "steps": [
      {
        "tool": "sentry.getIssue",
        "slots": {
          "issue_id": "$slots.sentry_issue_id"
        },
        "side_effects": "none"
      },
      {
        "tool": "github.readFile",
        "slots": {
          "repo": "Latimer-Woods-Tech/$slots.affected_app",
          "path": "$slots.billing_handler_file",
          "ref": "main"
        },
        "side_effects": "none"
      },
      {
        "tool": "github.comment",
        "slots": {
          "body": "**Supervisor triage — billing portal 400 in `$slots.affected_app`**\n\nSentry: $slots.sentry_issue_id\nError: $s1.exception_type — $s1.exception_value\nAffected user context: $s1.user\n\n**Root cause (pattern):** `handlePortal` short-circuits with HTTP 400 when `users.stripe_customer_id` is `null`. This happens when:\n- The Stripe `customer.created` webhook was missed or raced with session creation\n- The user was created before the webhook backfill logic was deployed (legacy accounts)\n\n**Fix pattern (from HumanDesign PR #152):**\nReplace the hard `if (!user.stripe_customer_id) return 400` guard with a three-step fallback:\n1. `users.stripe_customer_id` (primary)\n2. `subscriptions.stripe_customer_id` (webhook-written)\n3. `ensureCustomer()` — create/retrieve from Stripe API and backfill the `users` row\n\n**Handler state:** see $s2 for current implementation.\n\nA draft PR implementing the fallback chain will be opened for human review. This is a Red-tier action — Stripe billing code requires CODEOWNER approval before merge.\n\n_Run ID: $RUN_ID_\n"
        },
        "side_effects": "none"
      },
      {
        "tool": "github.addLabel",
        "slots": {
          "labels": [
            "status:triaged",
            "area:billing",
            "supervisor:human-action-required"
          ]
        },
        "side_effects": "none"
      },
      {
        "tool": "github.openPR",
        "slots": {
          "repo": "Latimer-Woods-Tech/$slots.affected_app",
          "base": "main",
          "head": "supervisor/billing-portal-400-$slots.affected_app",
          "title": "fix(billing): resolve portal 400 when stripe_customer_id is null",
          "body": "Closes #$triggers.issue_number\n\n**Root cause:** `handlePortal` returned HTTP 400 for paid users whose `stripe_customer_id` was `null` in the `users` table — typically caused by a missed or raced Stripe webhook.\n\n**Fix:** Implements a three-step fallback chain:\n1. `users.stripe_customer_id`\n2. `subscriptions.stripe_customer_id` (webhook-written)\n3. `ensureCustomer()` — create/retrieve from Stripe and backfill\n\nPattern source: HumanDesign PR #152.\nSentry: $slots.sentry_issue_id\nDiagnosis: see issue comment $s3.comment_url\n\n**Red-tier notice:** Touches Stripe billing code. CODEOWNER review required before merge.\n",
          "draft": true
        },
        "side_effects": "none"
      }
    ]
  },
  {
    "id": "fix-ci-package-auth",
    "tier": "yellow",
    "description": "CI fails during npm ci with E401 Unauthorized for @latimer-woods-tech/* private GitHub Packages because NODE_AUTH_TOKEN or packages:read permission is missing from a workflow.",
    "trigger_keywords": [
      "ci",
      "npm",
      "package",
      "auth",
      "401",
      "unauthorized",
      "PACKAGES_READ_TOKEN",
      "github-packages"
    ],
    "triggers": {
      "labels_any_of": [
        "bug",
        "area:ci"
      ],
      "title_pattern": "(npm.*401|401.*npm|package.*auth|E401.*latimer|@latimer-woods-tech.*unauthorized|PACKAGES_READ_TOKEN|packages:read)",
      "body_patterns": [
        "(E401|npm ci.*fail|PACKAGES_READ_TOKEN|NODE_AUTH_TOKEN|@latimer-woods-tech.*Unauthorized|packages: read)"
      ]
    },
    "steps": [
      {
        "tool": "github.readFile",
        "slots": {
          "repo": "Latimer-Woods-Tech/$slots.affected_repo",
          "path": "$slots.failing_workflow_path",
          "ref": "main"
        },
        "side_effects": "none"
      },
      {
        "tool": "github.comment",
        "slots": {
          "body": "**Supervisor diagnosis — CI package auth failure in `$slots.affected_repo`**\n\nFailing workflow: `$slots.failing_workflow_path`\nFailure mode: `$slots.failure_mode`\n\n**Root cause (pattern from HumanDesign PRs #133–#136):**\n`npm ci` on `@latimer-woods-tech/*` private packages fails with E401 when:\n1. `NODE_AUTH_TOKEN` is not set on the install step, OR\n2. The workflow `permissions` block is missing `packages: read`, OR\n3. The token fallback uses `secrets.GITHUB_TOKEN` instead of `github.token` (wrong context)\n\n**Required fix pattern:**\n```yaml\npermissions:\n  packages: read   # ← add this\n\nsteps:\n  - name: Install\n    run: npm ci\n    env:\n      NODE_AUTH_TOKEN: ${{ secrets.PACKAGES_READ_TOKEN || github.token }}  # ← github.token not secrets.GITHUB_TOKEN\n```\n\nCurrent workflow state: $s1.excerpt\n\nA draft PR will apply the fix to `$slots.failing_workflow_path`.\n\n_Run ID: $RUN_ID_\n"
        },
        "side_effects": "none"
      },
      {
        "tool": "github.openPR",
        "slots": {
          "repo": "Latimer-Woods-Tech/$slots.affected_repo",
          "base": "main",
          "head": "supervisor/ci-package-auth-$slots.affected_repo",
          "title": "fix(ci): add packages:read and NODE_AUTH_TOKEN to $slots.failing_workflow_path",
          "body": "Closes #$triggers.issue_number\n\n**Root cause:** `npm ci` fails with E401 for `@latimer-woods-tech/*` packages in `$slots.failing_workflow_path` due to `$slots.failure_mode`.\n\n**Fix:**\n- Adds `packages: read` to workflow/job `permissions`\n- Sets `NODE_AUTH_TOKEN: ${{ secrets.PACKAGES_READ_TOKEN || github.token }}` on the install step\n- Corrects fallback from `secrets.GITHUB_TOKEN` to `github.token` if applicable\n\nPattern source: HumanDesign PRs #133–#136.\nDiagnosis: $s2.comment_url\n",
          "draft": true
        },
        "side_effects": "none"
      }
    ]
  },
  {
    "id": "fix-csp-hash",
    "tier": "green",
    "description": "CSP violation caused by a stale inline-script SHA-256 hash in the Cloudflare Pages _headers file after a FOUC or inline script was changed.",
    "trigger_keywords": [
      "csp",
      "hash",
      "inline",
      "script",
      "headers",
      "sha256",
      "violation",
      "fouc"
    ],
    "triggers": {
      "labels_any_of": [
        "bug",
        "area:frontend",
        "area:security"
      ],
      "title_pattern": "(csp.*hash|hash.*csp|CSP.*sha256|inline.script.*violation|FOUC.*hash|_headers.*csp)",
      "body_patterns": [
        "(sha256-[A-Za-z0-9+/=]{43}|Content-Security-Policy|inline script.*violates|_headers)"
      ]
    },
    "steps": [
      {
        "tool": "github.readFile",
        "slots": {
          "repo": "Latimer-Woods-Tech/$slots.affected_app",
          "path": "$slots.headers_file",
          "ref": "main",
          "grep": "$slots.old_hash"
        },
        "side_effects": "none"
      },
      {
        "tool": "github.comment",
        "slots": {
          "body": "**Supervisor diagnosis — stale CSP hash in `$slots.affected_app`**\n\nFile: `$slots.headers_file`\nOld hash (stale): `$slots.old_hash`\nNew hash (browser-reported): `$slots.new_hash`\n\n**Root cause:** An inline script was updated (e.g. FOUC theme/density script) but the corresponding `sha256-*` hash in `Content-Security-Policy` was not updated.\n\n**Fix:** Replace `$slots.old_hash` with `$slots.new_hash` in `$slots.headers_file`. Single-line change.\n\nCurrent _headers excerpt:\n```\n$s1.excerpt\n```\n\nOpening a draft PR with the single-line hash swap.\n\n_Run ID: $RUN_ID_\n"
        },
        "side_effects": "none"
      },
      {
        "tool": "github.openPR",
        "slots": {
          "repo": "Latimer-Woods-Tech/$slots.affected_app",
          "base": "main",
          "head": "supervisor/csp-hash-$slots.affected_app",
          "title": "fix(csp): update inline-script sha256 hash in _headers",
          "body": "Closes #$triggers.issue_number\n\n**Root cause:** Stale CSP hash after inline-script change (e.g. FOUC script updated in a recent PR but `_headers` not updated).\n\n**Fix:** Replaces `$slots.old_hash` with `$slots.new_hash` in `$slots.headers_file`. Single-line, no logic changes.\n\n**Risk:** Green — static Cloudflare Pages headers file only.\n\nDiagnosis: $s2.comment_url\nPattern source: HumanDesign PR #74.\n",
          "draft": false
        },
        "side_effects": "none"
      }
    ]
  },
  {
    "id": "fix-mobile-layout",
    "tier": "yellow",
    "description": "Mobile viewport layout regression — typically a CSS grid/flex issue at ≤768px or ≤390px causing elements to overflow, stack incorrectly, or become unreachable by touch.",
    "trigger_keywords": [
      "mobile",
      "viewport",
      "layout",
      "responsive",
      "390px",
      "768px",
      "hamburger",
      "hero",
      "nav",
      "css"
    ],
    "triggers": {
      "labels_any_of": [
        "bug",
        "area:frontend"
      ],
      "title_pattern": "(mobile.*layout|layout.*mobile|mobile.*viewport|viewport.*break|hero.*390|nav.*mobile|hamburger|responsive.*break)",
      "body_patterns": [
        "(390px|768px|mobile.*viewport|@media.*max-width|overflow.*hidden|min-width:0|flex-shrink|grid.*1fr)"
      ]
    },
    "steps": [
      {
        "tool": "github.readFile",
        "slots": {
          "repo": "Latimer-Woods-Tech/$slots.affected_app",
          "path": "$slots.css_file",
          "ref": "main"
        },
        "side_effects": "none"
      },
      {
        "tool": "github.comment",
        "slots": {
          "body": "**Supervisor diagnosis — mobile layout regression in `$slots.affected_app`**\n\nBreakpoint: `$slots.breakpoint`\nCSS file: `$slots.css_file`\nIssue kind: `$slots.layout_issue_kind`\n\n**Known fix patterns (from HumanDesign PRs #150, #125, #119, #56):**\n- `grid-overflow`: add `min-width: 0` to the 1fr grid child; add `max-height` cap on media-child wraps at narrow widths\n- `nav-links-reachable-offscreen`: add `visibility: hidden` to the closed off-screen drawer; add `overflow-x: hidden` on the page root at `≤$slots.breakpoint`\n- `hero-column-blowout`: set `order: 2` (not `order: -1`) so video renders below text; add `width: 100%` on the video wrap\n- `tap-target-too-small`: wrap `<input>` in a 44×44px `<span>` overlay (WCAG 2.5.5); see PR #119 pattern\n- `horizontal-scroll`: add `overflow-x: hidden` to the nearest scrollable ancestor\n\nCSS file excerpt (current state):\n```css\n$s1.excerpt\n```\n\nA draft PR will be opened with the minimal targeted fix at `$slots.breakpoint`.\n\n_Run ID: $RUN_ID_\n"
        },
        "side_effects": "none"
      },
      {
        "tool": "github.openPR",
        "slots": {
          "repo": "Latimer-Woods-Tech/$slots.affected_app",
          "base": "main",
          "head": "supervisor/mobile-layout-$slots.affected_app",
          "title": "fix(mobile): resolve $slots.layout_issue_kind at $slots.breakpoint",
          "body": "Closes #$triggers.issue_number\n\n**Root cause:** CSS layout regression at `$slots.breakpoint` — `$slots.layout_issue_kind` in `$slots.css_file`.\n\n**Fix:** Targeted CSS-only change at the `@media (max-width: $slots.breakpoint)` breakpoint. No JS or markup changes (unless nav toggle requires it).\n\nPattern source: HumanDesign PRs #150, #125, #119.\nDiagnosis: see issue comment $s2.comment_url\n\n**Test plan:**\n- [ ] Resize browser to `$slots.breakpoint` — verify the layout issue is resolved\n- [ ] Resize to >768px — confirm desktop layout is unaffected\n- [ ] CI green on deploy-frontend workflow\n",
          "draft": true
        },
        "side_effects": "none"
      }
    ]
  },
  {
    "id": "fix-stripe-price-id",
    "tier": "red",
    "description": "Stripe checkout fails with 'No such price' or 'No such product' because a price ID env var is missing, set to a placeholder, or points to a test-mode ID in a live-mode context.",
    "trigger_keywords": [
      "stripe",
      "price",
      "product",
      "checkout",
      "no-such-price",
      "env",
      "secret",
      "placeholder"
    ],
    "triggers": {
      "labels_any_of": [
        "bug",
        "area:billing"
      ],
      "title_pattern": "(No such price|No such product|StripeInvalidRequest.*price|STRIPE_PRICE|price.*not.*found|checkout.*price)",
      "body_patterns": [
        "(No such price|No such product|price_[A-Za-z0-9]{14,}|STRIPE_PRICE_[A-Z_]+|createCheckoutSession)"
      ]
    },
    "steps": [
      {
        "tool": "sentry.getIssue",
        "slots": {
          "issue_id": "$slots.sentry_issue_id"
        },
        "side_effects": "none"
      },
      {
        "tool": "github.readFile",
        "slots": {
          "repo": "Latimer-Woods-Tech/$slots.affected_app",
          "path": "wrangler.jsonc",
          "ref": "main",
          "grep": "$slots.secret_name"
        },
        "side_effects": "none"
      },
      {
        "tool": "github.comment",
        "slots": {
          "body": "**Supervisor triage — Stripe price ID failure in `$slots.affected_app`**\n\nSentry: $slots.sentry_issue_id\nError: $s1.exception_value\nRejected price ID: extracted from $s1.exception_value\nSecret name: `$slots.secret_name`\nEnvironment: `$slots.environment`\n\n**Root cause (pattern from factory PR #347, HumanDesign):**\n`createCheckoutSession` received an empty, placeholder (`price_xxxxxxxxxxxxx`), or test-mode price ID when the Worker is running in live mode. This is a **config/secrets gap**, not a deleted Stripe price.\n\n**Verification steps (human action required):**\n1. Check the Stripe Dashboard → Products in the correct mode (live vs. test) for the price ID from the error.\n2. Run: `wrangler secret list --name <worker-name>` and verify `$slots.secret_name` is set.\n3. If missing or wrong: `wrangler secret put $slots.secret_name` and paste the correct `price_*` ID from Stripe.\n4. Deploy and verify `/health` returns 200, then retry checkout.\n\nwrangler.jsonc state: $s2.excerpt\n\n**Supervisor cannot write Worker secrets** (FRIDGE rule 8). Human action required.\n\n_Run ID: $RUN_ID_\n"
        },
        "side_effects": "none"
      },
      {
        "tool": "github.addLabel",
        "slots": {
          "labels": [
            "status:triaged",
            "area:billing",
            "supervisor:human-action-required",
            "needs-human:secrets"
          ]
        },
        "side_effects": "none"
      }
    ]
  },
  {
    "id": "governance-hardening",
    "tier": "green",
    "description": "Small governance, process, or hardening change: adding/updating labels, branch-protection tweaks, README/CLAUDE.md edits, workflow permission tightening, or AGENT_PROTOCOL propagation.",
    "trigger_keywords": [
      "governance",
      "hardening",
      "branch-protection",
      "label",
      "readme",
      "agent-protocol",
      "process",
      "chore"
    ],
    "triggers": {
      "labels_any_of": [
        "hardening",
        "governance",
        "chore"
      ],
      "title_pattern": "(governance|hardening|branch.protect|agent.protocol|AGENT_PROTOCOL|label.*add|add.*label|README.*update|CLAUDE\\.md)",
      "body_patterns": [
        "(branch.protect|label.*config|AGENT_PROTOCOL|CLAUDE\\.md|standing.orders|governance.*playbook)"
      ]
    },
    "steps": [
      {
        "tool": "factory_admin.repo.health",
        "slots": {
          "repo": "$slots.target_repo"
        },
        "side_effects": "none"
      },
      {
        "tool": "github.readFile",
        "slots": {
          "repo": "Latimer-Woods-Tech/$slots.target_repo",
          "path": "$slots.target_file",
          "ref": "main"
        },
        "side_effects": "none"
      },
      {
        "tool": "github.comment",
        "slots": {
          "body": "**Supervisor plan — governance hardening for `$slots.target_repo`**\n\nHardening kind: `$slots.hardening_kind`\nTarget file: `$slots.target_file`\n\n**Known patterns:**\n- `branch-protection`: add required-status-checks + dismiss-stale-reviews (factory PR #280 playbook)\n- `label-addition`: add label to `.github/labels.yml` and sync via label-sync workflow\n- `readme-update` / `claude-md-update`: propagate canonical standing orders from factory to app repo\n- `agent-protocol-propagation`: copy `.github/AGENT_PROTOCOL.md` + issue template from factory canonical (HumanDesign PR #122 pattern)\n- `workflow-permission`: tighten `permissions:` block on a specific workflow (principle of least privilege)\n\nCurrent file state: $s2.excerpt\n\nA draft PR will implement the change. Green-tier — no destructive mutations, docs/config only.\n\n_Run ID: $RUN_ID_\n"
        },
        "side_effects": "none"
      },
      {
        "tool": "github.openPR",
        "slots": {
          "repo": "Latimer-Woods-Tech/$slots.target_repo",
          "base": "main",
          "head": "supervisor/governance-$slots.hardening_kind-$slots.target_repo",
          "title": "chore(governance): $slots.hardening_kind for $slots.target_repo",
          "body": "Closes #$triggers.issue_number\n\n**Governance hardening:** `$slots.hardening_kind` in `$slots.target_repo`\n\nTarget file: `$slots.target_file`\n\nChanges are documentation/config only. No business logic affected.\nPattern source: factory PRs #280, #277, #276, #275; HumanDesign PR #122.\n\nPlan: see issue comment $s3.comment_url\n",
          "draft": true
        },
        "side_effects": "none"
      }
    ]
  },
  {
    "id": "migration-drift-fix",
    "tier": "yellow",
    "description": "",
    "trigger_keywords": [
      "migration",
      "drift",
      "schema",
      "column",
      "relation",
      "does not exist",
      "applied"
    ],
    "triggers": {
      "labels_any_of": [
        "bug",
        "area:database"
      ],
      "title_pattern": "Migration drift|column .* does not exist|relation .* does not exist|migration.*not applied",
      "body_patterns": [
        "(migration.*drift|column.*does not exist|relation.*does not exist|DatabaseError.*schema)"
      ]
    },
    "steps": [
      {
        "tool": "github.readFile",
        "slots": {
          "repo": "Latimer-Woods-Tech/$slots.affected_app",
          "path": "workers/src/db/migrations",
          "ref": "main",
          "grep": "$slots.missing_item"
        },
        "side_effects": "none"
      },
      {
        "tool": "github.readFile",
        "slots": {
          "repo": "Latimer-Woods-Tech/$slots.affected_app",
          "path": "workers/src/db/migrations",
          "ref": "main",
          "grep": "CREATE TABLE"
        },
        "side_effects": "none"
      },
      {
        "tool": "github.comment",
        "slots": {
          "body": "**Supervisor — migration drift runbook for `$slots.affected_app`**\n\nMissing: `$slots.missing_item`\nMigration scan result: $s1.matches\n\n**Root cause:** A migration that creates `$slots.missing_item` was merged to the repo but was not applied to the production Neon database.\n\n**Fix (human action required):**\n1. Connect to the production Neon branch for `$slots.affected_app` (see `docs/runbooks/database.md`).\n2. Run: `npm run migrate` from the app's `workers/` directory with `DATABASE_URL` set to the production connection string.\n3. Verify: query `SELECT column_name FROM information_schema.columns WHERE table_name = '<table>'` to confirm the column exists.\n4. Monitor Sentry for 15 min post-apply to confirm the error stops.\n\nThe supervisor cannot write to production databases (FRIDGE rule 8 — irreversible action). A CODEOWNER must execute this runbook.\n\nIf the migration is not in the repo (migration was never authored), file a new `bug` issue tagged `supervisor:approved-source` for the DB migration gap fix template.\n\n_Run ID: $RUN_ID_\n"
        },
        "side_effects": "none"
      },
      {
        "tool": "github.addLabel",
        "slots": {
          "labels": [
            "status:triaged",
            "area:database",
            "supervisor:human-action-required"
          ]
        },
        "side_effects": "none"
      }
    ]
  },
  {
    "id": "package-version-migration",
    "tier": "yellow",
    "description": "Migrate a worker/app to consume a @latimer-woods-tech/* package, removing the inline implementation",
    "trigger_keywords": [
      "area",
      "packages",
      "type",
      "refactor",
      "package",
      "version",
      "migration",
      "migrate",
      "workerapp",
      "consume",
      "latimerwoodstech",
      "removing"
    ],
    "triggers": {
      "labels_any_of": [
        "area:packages",
        "type:refactor"
      ],
      "title_pattern": "consume|migrate|@latimer-woods-tech|delete.*lib|remove.*inline"
    },
    "steps": [
      {
        "tool": "github.readFile",
        "slots": {
          "repo": "$slots.repo",
          "path": "$slots.file_to_delete"
        },
        "side_effects": "none"
      },
      {
        "tool": "github.readFile",
        "slots": {
          "repo": "$slots.repo",
          "path": "package.json"
        },
        "side_effects": "none"
      },
      {
        "tool": "github.openPR",
        "side_effects": "write-app"
      }
    ]
  },
  {
    "id": "reusable-workflow-rollout",
    "tier": "yellow",
    "description": "",
    "trigger_keywords": [
      "enhancement",
      "hardening",
      "reusable",
      "workflow",
      "rollout"
    ],
    "triggers": {
      "labels_any_of": [
        "enhancement",
        "hardening"
      ],
      "title_pattern": "(_app-ci|_app-deploy|reusable workflow|factory workflow)",
      "body_patterns": [
        "(?i)(replace|migrate|adopt|switch).*(workflow|deploy\\.yml|ci\\.yml)"
      ]
    },
    "steps": [
      {
        "tool": "factory_admin.repo.health",
        "slots": {
          "repo": "$slots.target_repo"
        },
        "side_effects": "none"
      },
      {
        "tool": "github.readFile",
        "slots": {
          "repo": "$slots.target_repo",
          "path": "$slots.existing_workflow_path",
          "ref": "main"
        },
        "side_effects": "none"
      },
      {
        "tool": "github.readFile",
        "slots": {
          "repo": "factory-admin",
          "path": ".github/workflows/_app-$slots.workflow_kind.yml",
          "ref": "main"
        },
        "side_effects": "none"
      },
      {
        "tool": "github.openPR",
        "slots": {
          "repo": "$slots.target_repo",
          "base": "main",
          "head": "supervisor/reusable-$slots.workflow_kind-rollout",
          "title": "Adopt factory reusable _app-$slots.workflow_kind workflow",
          "body": "Replaces `$slots.existing_workflow_path` with a thin caller that invokes\nfactory's reusable `_app-$slots.workflow_kind.yml`.\n\n- Removes: `$slots.existing_workflow_path`\n- Adds: `.github/workflows/$slots.workflow_kind.yml` (caller, ~5-10 lines)\n\nPattern source: VK-7, xpelevator/ijustus adoption.\n",
          "changes": [
            {
              "op": "delete",
              "path": "$slots.existing_workflow_path"
            },
            {
              "op": "create",
              "path": ".github/workflows/$slots.workflow_kind.yml",
              "from_template": "factory/callers/_app-$slots.workflow_kind.caller.yml",
              "inputs_from": "$s2.content",
              "reusable_signature": "$s3.content"
            }
          ],
          "labels": [
            "enhancement",
            "hardening",
            "supervisor"
          ]
        },
        "side_effects": "none"
      }
    ]
  },
  {
    "id": "security-codeql-fix",
    "tier": "yellow",
    "description": "",
    "trigger_keywords": [
      "area",
      "security",
      "bug",
      "codeql",
      "fix"
    ],
    "triggers": {
      "labels_any_of": [
        "area:security",
        "bug"
      ],
      "title_pattern": "(SEC-\\d|codeql|code.scan|security.alert|fix.*codeql|codeql.*fix)",
      "body_patterns": [
        "(codeql|code scanning alert|security alert)"
      ]
    },
    "steps": [
      {
        "tool": "github.readFile",
        "slots": {
          "repo": "factory",
          "path": "$slots.file_path",
          "ref": "main"
        },
        "side_effects": "none"
      },
      {
        "tool": "github.comment",
        "slots": {
          "issue_ref": "$triggers.issue_number",
          "body": "Supervisor diagnosis for $slots.alert_id\n\nFile: `$slots.file_path`\nViolation type: `$slots.violation_type`\n\nApplying minimal targeted fix. Will open a draft PR for review."
        },
        "side_effects": "none"
      },
      {
        "tool": "github.openPR",
        "slots": {
          "repo": "factory",
          "base": "main",
          "head": "supervisor/codeql-$slots.alert_id",
          "title": "fix(security): resolve CodeQL alert $slots.alert_id in $slots.file_path",
          "body": "Closes #$triggers.issue_number\n\nMinimal targeted fix for CodeQL alert `$slots.alert_id` ($slots.violation_type) in `$slots.file_path`.\n\nDiagnosis: see issue comment $s2.comment_url\n\nThis PR was generated by the supervisor. Human review required before merge.",
          "draft": true
        },
        "side_effects": "none"
      }
    ]
  },
  {
    "id": "sentry-stripe-error-triage",
    "tier": "yellow",
    "description": "",
    "trigger_keywords": [
      "stripe",
      "payment",
      "webhook",
      "subscription",
      "billing",
      "price",
      "checkout"
    ],
    "triggers": {
      "labels_any_of": [
        "bug",
        "source:sentry"
      ],
      "title_pattern": "StripeInvalidRequest|StripeCardError|No such (price|customer|product)|stripe.*error",
      "body_patterns": [
        "(StripeInvalidRequest|StripeCardError|stripe\\.com/docs/error-codes)"
      ]
    },
    "steps": [
      {
        "tool": "sentry.getIssue",
        "slots": {
          "issue_id": "$slots.sentry_issue_id"
        },
        "side_effects": "none"
      },
      {
        "tool": "github.comment",
        "slots": {
          "body": "**Supervisor triage — Stripe error `$slots.stripe_error_code`**\n\nSentry: $slots.sentry_issue_id\nApp: $slots.affected_app\nError: $s1.exception_type — $s1.exception_value\n\n**Runbook:**\n- `no_such_price` / `no_such_product` — price/product ID in code doesn't exist in Stripe. Check if the live-mode ID was accidentally replaced with a test-mode ID. Look up `$s1.exception_value` in the Stripe dashboard and update the env var or DB row.\n- `no_such_customer` — customer record deleted in Stripe or created in wrong mode. Check `stripe_customer_id` column for the user mentioned in the stack trace.\n- `card_declined` / `insufficient_funds` — user-facing; no code change needed. Check if webhook handler marks the subscription as `past_due` correctly.\n- `invalid_request_error` — inspect the Stripe API call arguments in the stack frame. Common cause: empty/null fields passed to the API.\n\n**Next step:** A CODEOWNER should investigate the linked Sentry issue and apply the appropriate fix. If a code change is needed, file a new issue tagged `supervisor:approved-source` with the specific file + line.\n\n_Run ID: $RUN_ID_\n"
        },
        "side_effects": "none"
      },
      {
        "tool": "github.addLabel",
        "slots": {
          "labels": [
            "status:triaged",
            "area:billing"
          ]
        },
        "side_effects": "none"
      }
    ]
  },
  {
    "id": "sentry-triage-new-issue",
    "tier": "yellow",
    "description": "",
    "trigger_keywords": [
      "bug",
      "sentry",
      "triage",
      "new",
      "issue"
    ],
    "triggers": {
      "labels_any_of": [
        "bug",
        "sentry"
      ],
      "title_pattern": "^Sentry:",
      "body_patterns": [
        "sentry\\.io/.*/issues/"
      ]
    },
    "steps": [
      {
        "tool": "sentry.getIssue",
        "slots": {
          "short_id": "$slots.sentry_short_id"
        },
        "side_effects": "none"
      },
      {
        "tool": "github.readFile",
        "slots": {
          "repo": "$slots.repo_name",
          "path": "$s1.culprit_file",
          "ref": "$s1.release_sha"
        },
        "side_effects": "none"
      },
      {
        "tool": "github.comment",
        "slots": {
          "issue_ref": "$triggers.issue_number",
          "body": "Supervisor diagnosis for $slots.sentry_short_id\n\nCulprit: $s1.culprit\nTop frame: $s1.top_frame\nFile excerpt:\n$s2.excerpt\n\nProposed remediation mode: $slots.fix_mode"
        },
        "side_effects": "none"
      },
      {
        "tool": "github.addLabel",
        "slots": {
          "issue_ref": "$triggers.issue_number",
          "label": "supervisor/triaged"
        },
        "side_effects": "none"
      },
      {
        "tool": "github.openPR",
        "slots": {
          "repo": "$slots.repo_name",
          "base": "main",
          "head": "supervisor/sentry-$slots.sentry_short_id",
          "title": "fix: $s1.culprit (Sentry $slots.sentry_short_id)",
          "body": "Automated small-patch proposal for Sentry $slots.sentry_short_id.\n\nDiagnosis: see issue comment $s3.comment_url\nPatch size constraint: <5 lines.\nMode: $slots.fix_mode\n\nRequires human review before merge.",
          "draft": true
        },
        "side_effects": "none"
      }
    ]
  },
  {
    "id": "syn-package-migration",
    "tier": "yellow",
    "description": "",
    "trigger_keywords": [
      "dependencies",
      "packages",
      "migration",
      "refactor",
      "syn",
      "package"
    ],
    "triggers": {
      "labels_any_of": [
        "dependencies",
        "packages",
        "migration",
        "refactor"
      ],
      "title_pattern": "^(feat|refactor|chore)\\(.*\\):\\s*(SYN-|.*package|.*extract)",
      "body_patterns": [
        "(?is)(package|migration|extract|workspace|publish|composite action|shared)"
      ]
    },
    "steps": [
      {
        "tool": "github.comment",
        "slots": {
          "issue": "$issue.number",
          "body": "Supervisor triage plan for SYN/package migration.\n- Confirm API compatibility and semver impact\n- Verify import path + build/test changes across affected apps\n- Validate release, changelog, and rollback plan\n- Require human approval before execution\n"
        },
        "side_effects": "none"
      }
    ]
  },
  {
    "id": "user-account-suspend",
    "tier": "yellow",
    "description": "",
    "trigger_keywords": [
      "suspend",
      "ban",
      "block",
      "abuse",
      "fraud",
      "spam",
      "violat"
    ],
    "triggers": {
      "labels_any_of": [
        "moderation",
        "abuse",
        "fraud"
      ],
      "title_pattern": "Suspend (user|account)|Account suspension|Fraudulent (account|activity)",
      "body_patterns": [
        "(suspend|ban|block|abuse|fraud|spam|violat)"
      ]
    },
    "steps": [
      {
        "tool": "humandesign.user.lookup",
        "slots": {
          "id": "$slots.user_id"
        },
        "side_effects": "none"
      },
      {
        "tool": "github.comment",
        "slots": {
          "body": "**Supervisor — pre-suspension verification**\n\nUser `$slots.user_id` found:\n- Email: $s1.email\n- Tier: $s1.tier\n- Status: $s1.status\n- Created: $s1.created_at\n\nProposed action: **suspend** with reason: \"$slots.reason\"\n\n⚠️ This action requires CODEOWNER approval. React ✅ to this comment to authorize.\nOnce approved, the supervisor will call `$slots.affected_app.user.suspend`.\n\n_Run ID: $RUN_ID_\n"
        },
        "side_effects": "none"
      },
      {
        "tool": "humandesign.user.suspend",
        "slots": {
          "id": "$slots.user_id",
          "reason": "$slots.reason"
        },
        "side_effects": "none"
      },
      {
        "tool": "github.addLabel",
        "slots": {
          "labels": [
            "status:done",
            "moderation:suspended"
          ]
        },
        "side_effects": "none"
      }
    ]
  },
  {
    "id": "ux-regression-triage",
    "tier": "yellow",
    "description": "",
    "trigger_keywords": [
      "accessibility",
      "bug",
      "regression",
      "triage"
    ],
    "triggers": {
      "labels_any_of": [
        "ux",
        "accessibility",
        "bug"
      ],
      "title_pattern": "^(\\[P[0-3]\\]\\[UX\\]|ux|bug)",
      "body_patterns": [
        "(?is)(repro|steps|expected|actual|viewport|mobile|a11y|accessibility)"
      ]
    },
    "steps": [
      {
        "tool": "github.comment",
        "slots": {
          "issue": "$issue.number",
          "body": "Supervisor triage plan for UX regression.\n- Confirm reproducibility (device + viewport)\n- Capture expected vs actual behavior\n- Propose minimal-risk fix path\n- Escalate P0/P1 for immediate assignment\n"
        },
        "side_effects": "none"
      }
    ]
  },
  {
    "id": "worker-health-degraded",
    "tier": "green",
    "description": "",
    "trigger_keywords": [
      "health",
      "degraded",
      "down",
      "503",
      "502",
      "timeout",
      "unreachable",
      "synthetic monitor"
    ],
    "triggers": {
      "labels_any_of": [
        "incident",
        "monitoring",
        "source:synthetic-monitor"
      ],
      "title_pattern": "Worker (health|degraded|down|503|502)|Synthetic monitor (fail|alert)|/health (returning|returning 5)",
      "body_patterns": [
        "(/health.*5[0-9]{2}|synthetic.*monitor.*fail|worker.*unreachable)"
      ]
    },
    "steps": [
      {
        "tool": "factory-admin.observability.summary",
        "slots": {},
        "side_effects": "none"
      },
      {
        "tool": "github.comment",
        "slots": {
          "body": "**Supervisor — worker health degradation triage**\n\nAffected worker: `$slots.affected_worker` (HTTP $slots.error_code)\nObservability summary: $s1.summary\n\n**Immediate checks (human):**\n1. `curl -I https://$slots.affected_worker.adrper79.workers.dev/health` — confirm current status\n2. Check Cloudflare dashboard for the worker at https://dash.cloudflare.com\n3. Check Sentry project for `$slots.affected_worker` for recent error spike\n4. If 502/503: check if a recent deployment is the cause via `wrangler rollback`\n\n**Rollback command (if deployment-related):**\n```\ncd apps/$slots.affected_worker && wrangler rollback\n```\n\n**Escalation:** If the worker is still degraded after 15 min, page on-call via Pushover.\n\nThe supervisor cannot invoke `wrangler rollback` (FRIDGE rule 8 — irreversible infra action). A CODEOWNER must execute this runbook.\n\n_Run ID: $RUN_ID_\n"
        },
        "side_effects": "none"
      },
      {
        "tool": "github.addLabel",
        "slots": {
          "labels": [
            "status:triaged",
            "incident",
            "supervisor:human-action-required"
          ]
        },
        "side_effects": "none"
      }
    ]
  },
  {
    "id": "wrangler-config-drift-fix",
    "tier": "yellow",
    "description": "",
    "trigger_keywords": [
      "bug",
      "wrangler",
      "config",
      "drift",
      "fix"
    ],
    "triggers": {
      "labels_any_of": [
        "bug"
      ],
      "title_pattern": "(wrangler|binding|Hyperdrive)",
      "body_patterns": [
        "(wrangler\\.jsonc|binding|hyperdrive|kv|r2|d1|durable_object)"
      ]
    },
    "steps": [
      {
        "tool": "github.readFile",
        "slots": {
          "repo": "$slots.app_name",
          "path": "wrangler.jsonc"
        },
        "side_effects": "none"
      },
      {
        "tool": "cloudflare.listWorkers",
        "slots": {
          "filter_binding_kind": "$slots.binding_kind",
          "filter_binding_id": "$slots.binding_id"
        },
        "side_effects": "none"
      },
      {
        "tool": "factory_admin.worker.status",
        "slots": {
          "worker": "$slots.worker_name"
        },
        "side_effects": "none"
      },
      {
        "tool": "github.openPR",
        "slots": {
          "repo": "$slots.app_name",
          "branch": "supervisor/wrangler-drift-$slots.worker_name",
          "title": "fix(wrangler): correct $slots.binding_kind binding for $slots.worker_name",
          "body": "Automated fix: wrangler.jsonc referenced a stale $slots.binding_kind binding. Updated to the resolved ID from cloudflare.listWorkers (see $s2). Current file state captured in $s1.",
          "files": [
            {
              "path": "wrangler.jsonc",
              "from_step": "s1",
              "patch_kind": "update_binding",
              "binding_kind": "$slots.binding_kind",
              "new_binding_id": "$s2.resolved_id"
            }
          ]
        },
        "side_effects": "none"
      }
    ]
  }
];
