// AUTO-GENERATED by scripts/generate-supervisor-templates.mjs
// DO NOT EDIT DIRECTLY — edit docs/supervisor/plans/*.yml instead,
// then run: node scripts/generate-supervisor-templates.mjs
//
// Generated: 2026-05-06T05:36:00.563Z
// Source files: db-migration-gap-fix.yml, deps-bump-minor-patch.yml, docs-naming-convention.yml, feat-ci-workflow.yml, migration-drift-fix.yml, package-version-migration.yml, reusable-workflow-rollout.yml, security-codeql-fix.yml, sentry-stripe-error-triage.yml, sentry-triage-new-issue.yml, syn-package-migration.yml, user-account-suspend.yml, ux-regression-triage.yml, worker-health-degraded.yml, wrangler-config-drift-fix.yml

import type { Template } from './load';

export const GENERATED_TEMPLATES: Template[] = [
  {
    "id": "db-migration-gap-fix",
    "tier": "yellow",
    "description": "",
    "trigger_keywords": [
      "bug",
      "migration",
      "gap",
      "fix"
    ],
    "triggers": {
      "labels_any_of": [
        "bug"
      ],
      "title_pattern": "^(MIGRATION:|DatabaseError|column .* does not exist)",
      "body_patterns": [
        "(sentry\\.io/|DatabaseError|does not exist)"
      ]
    },
    "steps": [
      {
        "tool": "sentry.getIssue",
        "slots": {
          "issue_id": "$slots.sentry_issue_id"
        },
        "side_effects": "none"
      },
      {
        "tool": "github.readFile",
        "slots": {
          "path": "workers/src/db/migrations/",
          "ref": "main",
          "grep": "$slots.column_or_relation"
        },
        "side_effects": "none"
      },
      {
        "tool": "github.readFile",
        "slots": {
          "path": "workers/src/db/migrations/",
          "ref": "main",
          "grep": "$slots.table_name"
        },
        "side_effects": "none"
      },
      {
        "tool": "github.comment",
        "slots": {
          "body": "Supervisor runbook: apply migrations that introduce `$slots.table_name.$slots.column_or_relation` on prod. Migration authored in repo (see $s2.matches, $s3.matches) but not applied in prod database. Human action required: run `psql` against prod replica of the affected worker DB and apply migrations N..M in order. Sentry: $slots.sentry_issue_id. If no matching migration is found in $s2/$s3, reclassify this issue to tier:red (migration authoring needed)."
        },
        "side_effects": "none"
      },
      {
        "tool": "github.addLabel",
        "slots": {
          "label": "needs-human:db-migration"
        },
        "side_effects": "none"
      }
    ]
  },
  {
    "id": "deps-bump-minor-patch",
    "tier": "green",
    "description": "",
    "trigger_keywords": [
      "dependencies",
      "deps",
      "bump",
      "minor",
      "patch"
    ],
    "triggers": {
      "labels_any_of": [
        "dependencies"
      ],
      "title_pattern": "^(chore\\(deps\\):|Bump)",
      "body_patterns": [
        "(?i)bumps?\\s+\\[?[@A-Za-z0-9._/-]+\\]?\\s+from\\s+v?\\d+\\.\\d+\\.\\d+\\s+to\\s+v?\\d+\\.\\d+\\.\\d+"
      ]
    },
    "steps": [
      {
        "tool": "github.readFile",
        "slots": {
          "repo": "$slots.repo_name",
          "path": "package.json"
        },
        "side_effects": "none"
      },
      {
        "tool": "github.readFile",
        "slots": {
          "repo": "$slots.repo_name",
          "path": "package-lock.json"
        },
        "side_effects": "none"
      },
      {
        "tool": "github.addLabel",
        "slots": {
          "repo": "$slots.repo_name",
          "label": "auto-merge-green"
        },
        "side_effects": "none"
      },
      {
        "tool": "github.comment",
        "slots": {
          "repo": "$slots.repo_name",
          "body": "Green-tier supervisor approving $slots.bump_kind bump of $slots.package_name from $slots.from_version to $slots.to_version. CI is green and no security advisory blocks."
        },
        "side_effects": "none"
      },
      {
        "tool": "github.mergePR",
        "slots": {
          "repo": "$slots.repo_name",
          "merge_method": "squash"
        },
        "side_effects": "none"
      }
    ]
  },
  {
    "id": "docs-naming-convention",
    "tier": "green",
    "description": "",
    "trigger_keywords": [
      "docs",
      "documentation",
      "hardening",
      "naming",
      "convention"
    ],
    "triggers": {
      "labels_any_of": [
        "docs",
        "documentation",
        "hardening"
      ],
      "title_pattern": "^docs[(:]",
      "body_patterns": [
        "(?is)path\\s*[:=]\\s*(docs|documents)/",
        "(?is)(content|body)\\s*[:=]"
      ]
    },
    "steps": [
      {
        "tool": "github.readFile",
        "slots": {
          "path": "$slots.parent_dir",
          "ref": "main"
        },
        "side_effects": "none"
      },
      {
        "tool": "github.readFile",
        "slots": {
          "path": "$slots.target_path",
          "ref": "main",
          "allow_missing": true
        },
        "side_effects": "none"
      },
      {
        "tool": "github.openPR",
        "slots": {
          "branch": "$slots.branch_name",
          "base": "main",
          "title": "$slots.commit_message",
          "commit_message": "$slots.commit_message",
          "files": [
            {
              "path": "$slots.target_path",
              "content": "$slots.doc_body"
            }
          ],
          "body": "Auto-drafted by supervisor for cluster `docs-naming-convention`.\nScope: $slots.scope\nTarget: $slots.target_path\nSource issue: see linked issue.\n",
          "labels": [
            "docs",
            "supervisor",
            "tier-green"
          ]
        },
        "side_effects": "none"
      },
      {
        "tool": "github.comment",
        "slots": {
          "pr": "$s3.number",
          "body": "Supervisor opened this docs PR from the linked issue. CI runs docs-lint + credential-scrub only; no code paths touched."
        },
        "side_effects": "none"
      }
    ]
  },
  {
    "id": "feat-ci-workflow",
    "tier": "yellow",
    "description": "",
    "trigger_keywords": [
      "engineering",
      "hardening",
      "enhancement",
      "feat",
      "workflow"
    ],
    "triggers": {
      "labels_any_of": [
        "engineering",
        "hardening",
        "enhancement"
      ],
      "title_pattern": "(feat\\(ci\\)|feat\\(triage\\)|feat\\(review\\)|feat\\(reliability\\)|feat\\(process\\)|chore\\(ci\\)|chore\\(process\\)|chore\\(governance\\))",
      "body_patterns": [
        "(github actions|workflow|\\.github/workflows|ci check|path\\.based|required\\.check)"
      ]
    },
    "steps": [
      {
        "tool": "github.readFile",
        "slots": {
          "repo": "factory",
          "path": ".github/workflows/COORDINATION.md",
          "ref": "main"
        },
        "side_effects": "none"
      },
      {
        "tool": "github.comment",
        "slots": {
          "issue_ref": "$triggers.issue_number",
          "body": "Supervisor plan for `$slots.workflow_name`\n\n**Trigger events:** `$slots.trigger_events`\n**Description:** $slots.description\n\nDrafting workflow YAML following Factory conventions. Will open a draft PR.\n\n@adrper79-dot — React ✅ to proceed, or comment with changes needed."
        },
        "side_effects": "none"
      },
      {
        "tool": "github.openPR",
        "slots": {
          "repo": "factory",
          "base": "main",
          "head": "supervisor/ci-$slots.workflow_name",
          "title": "feat(ci): add $slots.workflow_name workflow",
          "body": "Closes #$triggers.issue_number\n\nAdds `.github/workflows/$slots.workflow_name.yml` implementing: $slots.description\n\nFollows Factory App token pattern and COORDINATION.md conventions.\n\nGenerated by supervisor. Human review required before merge.",
          "draft": true
        },
        "side_effects": "none"
      }
    ]
  },
  {
    "id": "migration-drift-fix",
    "tier": "yellow",
    "description": "",
    "trigger_keywords": [
      "migration",
      "drift",
      "schema",
      "column",
      "relation",
      "does not exist",
      "applied"
    ],
    "triggers": {
      "labels_any_of": [
        "bug",
        "area:database"
      ],
      "title_pattern": "Migration drift|column .* does not exist|relation .* does not exist|migration.*not applied",
      "body_patterns": [
        "(migration.*drift|column.*does not exist|relation.*does not exist|DatabaseError.*schema)"
      ]
    },
    "steps": [
      {
        "tool": "github.readFile",
        "slots": {
          "repo": "Latimer-Woods-Tech/$slots.affected_app",
          "path": "workers/src/db/migrations",
          "ref": "main",
          "grep": "$slots.missing_item"
        },
        "side_effects": "none"
      },
      {
        "tool": "github.readFile",
        "slots": {
          "repo": "Latimer-Woods-Tech/$slots.affected_app",
          "path": "workers/src/db/migrations",
          "ref": "main",
          "grep": "CREATE TABLE"
        },
        "side_effects": "none"
      },
      {
        "tool": "github.comment",
        "slots": {
          "body": "**Supervisor — migration drift runbook for `$slots.affected_app`**\n\nMissing: `$slots.missing_item`\nMigration scan result: $s1.matches\n\n**Root cause:** A migration that creates `$slots.missing_item` was merged to the repo but was not applied to the production Neon database.\n\n**Fix (human action required):**\n1. Connect to the production Neon branch for `$slots.affected_app` (see `docs/runbooks/database.md`).\n2. Run: `npm run migrate` from the app's `workers/` directory with `DATABASE_URL` set to the production connection string.\n3. Verify: query `SELECT column_name FROM information_schema.columns WHERE table_name = '<table>'` to confirm the column exists.\n4. Monitor Sentry for 15 min post-apply to confirm the error stops.\n\nThe supervisor cannot write to production databases (FRIDGE rule 8 — irreversible action). A CODEOWNER must execute this runbook.\n\nIf the migration is not in the repo (migration was never authored), file a new `bug` issue tagged `supervisor:approved-source` for the DB migration gap fix template.\n\n_Run ID: $RUN_ID_\n"
        },
        "side_effects": "none"
      },
      {
        "tool": "github.addLabel",
        "slots": {
          "labels": [
            "status:triaged",
            "area:database",
            "supervisor:human-action-required"
          ]
        },
        "side_effects": "none"
      }
    ]
  },
  {
    "id": "package-version-migration",
    "tier": "yellow",
    "description": "Migrate a worker/app to consume a @latimer-woods-tech/* package, removing the inline implementation",
    "trigger_keywords": [
      "area",
      "packages",
      "type",
      "refactor",
      "package",
      "version",
      "migration",
      "migrate",
      "workerapp",
      "consume",
      "latimerwoodstech",
      "removing"
    ],
    "triggers": {
      "labels_any_of": [
        "area:packages",
        "type:refactor"
      ],
      "title_pattern": "consume|migrate|@latimer-woods-tech|delete.*lib|remove.*inline"
    },
    "steps": [
      {
        "tool": "github.readFile",
        "slots": {
          "repo": "$slots.repo",
          "path": "$slots.file_to_delete"
        },
        "side_effects": "none"
      },
      {
        "tool": "github.readFile",
        "slots": {
          "repo": "$slots.repo",
          "path": "package.json"
        },
        "side_effects": "none"
      },
      {
        "tool": "github.openPR",
        "side_effects": "write-app"
      }
    ]
  },
  {
    "id": "reusable-workflow-rollout",
    "tier": "yellow",
    "description": "",
    "trigger_keywords": [
      "enhancement",
      "hardening",
      "reusable",
      "workflow",
      "rollout"
    ],
    "triggers": {
      "labels_any_of": [
        "enhancement",
        "hardening"
      ],
      "title_pattern": "(_app-ci|_app-deploy|reusable workflow|factory workflow)",
      "body_patterns": [
        "(?i)(replace|migrate|adopt|switch).*(workflow|deploy\\.yml|ci\\.yml)"
      ]
    },
    "steps": [
      {
        "tool": "factory_admin.repo.health",
        "slots": {
          "repo": "$slots.target_repo"
        },
        "side_effects": "none"
      },
      {
        "tool": "github.readFile",
        "slots": {
          "repo": "$slots.target_repo",
          "path": "$slots.existing_workflow_path",
          "ref": "main"
        },
        "side_effects": "none"
      },
      {
        "tool": "github.readFile",
        "slots": {
          "repo": "factory-admin",
          "path": ".github/workflows/_app-$slots.workflow_kind.yml",
          "ref": "main"
        },
        "side_effects": "none"
      },
      {
        "tool": "github.openPR",
        "slots": {
          "repo": "$slots.target_repo",
          "base": "main",
          "head": "supervisor/reusable-$slots.workflow_kind-rollout",
          "title": "Adopt factory reusable _app-$slots.workflow_kind workflow",
          "body": "Replaces `$slots.existing_workflow_path` with a thin caller that invokes\nfactory's reusable `_app-$slots.workflow_kind.yml`.\n\n- Removes: `$slots.existing_workflow_path`\n- Adds: `.github/workflows/$slots.workflow_kind.yml` (caller, ~5-10 lines)\n\nPattern source: VK-7, xpelevator/ijustus adoption.\n",
          "changes": [
            {
              "op": "delete",
              "path": "$slots.existing_workflow_path"
            },
            {
              "op": "create",
              "path": ".github/workflows/$slots.workflow_kind.yml",
              "from_template": "factory/callers/_app-$slots.workflow_kind.caller.yml",
              "inputs_from": "$s2.content",
              "reusable_signature": "$s3.content"
            }
          ],
          "labels": [
            "enhancement",
            "hardening",
            "supervisor"
          ]
        },
        "side_effects": "none"
      }
    ]
  },
  {
    "id": "security-codeql-fix",
    "tier": "yellow",
    "description": "",
    "trigger_keywords": [
      "area",
      "security",
      "bug",
      "codeql",
      "fix"
    ],
    "triggers": {
      "labels_any_of": [
        "area:security",
        "bug"
      ],
      "title_pattern": "(SEC-\\d|codeql|code.scan|security.alert|fix.*codeql|codeql.*fix)",
      "body_patterns": [
        "(codeql|code scanning alert|security alert)"
      ]
    },
    "steps": [
      {
        "tool": "github.readFile",
        "slots": {
          "repo": "factory",
          "path": "$slots.file_path",
          "ref": "main"
        },
        "side_effects": "none"
      },
      {
        "tool": "github.comment",
        "slots": {
          "issue_ref": "$triggers.issue_number",
          "body": "Supervisor diagnosis for $slots.alert_id\n\nFile: `$slots.file_path`\nViolation type: `$slots.violation_type`\n\nApplying minimal targeted fix. Will open a draft PR for review."
        },
        "side_effects": "none"
      },
      {
        "tool": "github.openPR",
        "slots": {
          "repo": "factory",
          "base": "main",
          "head": "supervisor/codeql-$slots.alert_id",
          "title": "fix(security): resolve CodeQL alert $slots.alert_id in $slots.file_path",
          "body": "Closes #$triggers.issue_number\n\nMinimal targeted fix for CodeQL alert `$slots.alert_id` ($slots.violation_type) in `$slots.file_path`.\n\nDiagnosis: see issue comment $s2.comment_url\n\nThis PR was generated by the supervisor. Human review required before merge.",
          "draft": true
        },
        "side_effects": "none"
      }
    ]
  },
  {
    "id": "sentry-stripe-error-triage",
    "tier": "yellow",
    "description": "",
    "trigger_keywords": [
      "stripe",
      "payment",
      "webhook",
      "subscription",
      "billing",
      "price",
      "checkout"
    ],
    "triggers": {
      "labels_any_of": [
        "bug",
        "source:sentry"
      ],
      "title_pattern": "StripeInvalidRequest|StripeCardError|No such (price|customer|product)|stripe.*error",
      "body_patterns": [
        "(StripeInvalidRequest|StripeCardError|stripe\\.com/docs/error-codes)"
      ]
    },
    "steps": [
      {
        "tool": "sentry.getIssue",
        "slots": {
          "issue_id": "$slots.sentry_issue_id"
        },
        "side_effects": "none"
      },
      {
        "tool": "github.comment",
        "slots": {
          "body": "**Supervisor triage — Stripe error `$slots.stripe_error_code`**\n\nSentry: $slots.sentry_issue_id\nApp: $slots.affected_app\nError: $s1.exception_type — $s1.exception_value\n\n**Runbook:**\n- `no_such_price` / `no_such_product` — price/product ID in code doesn't exist in Stripe. Check if the live-mode ID was accidentally replaced with a test-mode ID. Look up `$s1.exception_value` in the Stripe dashboard and update the env var or DB row.\n- `no_such_customer` — customer record deleted in Stripe or created in wrong mode. Check `stripe_customer_id` column for the user mentioned in the stack trace.\n- `card_declined` / `insufficient_funds` — user-facing; no code change needed. Check if webhook handler marks the subscription as `past_due` correctly.\n- `invalid_request_error` — inspect the Stripe API call arguments in the stack frame. Common cause: empty/null fields passed to the API.\n\n**Next step:** A CODEOWNER should investigate the linked Sentry issue and apply the appropriate fix. If a code change is needed, file a new issue tagged `supervisor:approved-source` with the specific file + line.\n\n_Run ID: $RUN_ID_\n"
        },
        "side_effects": "none"
      },
      {
        "tool": "github.addLabel",
        "slots": {
          "labels": [
            "status:triaged",
            "area:billing"
          ]
        },
        "side_effects": "none"
      }
    ]
  },
  {
    "id": "sentry-triage-new-issue",
    "tier": "yellow",
    "description": "",
    "trigger_keywords": [
      "bug",
      "sentry",
      "triage",
      "new",
      "issue"
    ],
    "triggers": {
      "labels_any_of": [
        "bug",
        "sentry"
      ],
      "title_pattern": "^Sentry:",
      "body_patterns": [
        "sentry\\.io/.*/issues/"
      ]
    },
    "steps": [
      {
        "tool": "sentry.getIssue",
        "slots": {
          "short_id": "$slots.sentry_short_id"
        },
        "side_effects": "none"
      },
      {
        "tool": "github.readFile",
        "slots": {
          "repo": "$slots.repo_name",
          "path": "$s1.culprit_file",
          "ref": "$s1.release_sha"
        },
        "side_effects": "none"
      },
      {
        "tool": "github.comment",
        "slots": {
          "issue_ref": "$triggers.issue_number",
          "body": "Supervisor diagnosis for $slots.sentry_short_id\n\nCulprit: $s1.culprit\nTop frame: $s1.top_frame\nFile excerpt:\n$s2.excerpt\n\nProposed remediation mode: $slots.fix_mode"
        },
        "side_effects": "none"
      },
      {
        "tool": "github.addLabel",
        "slots": {
          "issue_ref": "$triggers.issue_number",
          "label": "supervisor/triaged"
        },
        "side_effects": "none"
      },
      {
        "tool": "github.openPR",
        "slots": {
          "repo": "$slots.repo_name",
          "base": "main",
          "head": "supervisor/sentry-$slots.sentry_short_id",
          "title": "fix: $s1.culprit (Sentry $slots.sentry_short_id)",
          "body": "Automated small-patch proposal for Sentry $slots.sentry_short_id.\n\nDiagnosis: see issue comment $s3.comment_url\nPatch size constraint: <5 lines.\nMode: $slots.fix_mode\n\nRequires human review before merge.",
          "draft": true
        },
        "side_effects": "none"
      }
    ]
  },
  {
    "id": "syn-package-migration",
    "tier": "yellow",
    "description": "",
    "trigger_keywords": [
      "dependencies",
      "packages",
      "migration",
      "refactor",
      "syn",
      "package"
    ],
    "triggers": {
      "labels_any_of": [
        "dependencies",
        "packages",
        "migration",
        "refactor"
      ],
      "title_pattern": "^(feat|refactor|chore)\\(.*\\):\\s*(SYN-|.*package|.*extract)",
      "body_patterns": [
        "(?is)(package|migration|extract|workspace|publish|composite action|shared)"
      ]
    },
    "steps": [
      {
        "tool": "github.comment",
        "slots": {
          "issue": "$issue.number",
          "body": "Supervisor triage plan for SYN/package migration.\n- Confirm API compatibility and semver impact\n- Verify import path + build/test changes across affected apps\n- Validate release, changelog, and rollback plan\n- Require human approval before execution\n"
        },
        "side_effects": "none"
      }
    ]
  },
  {
    "id": "user-account-suspend",
    "tier": "yellow",
    "description": "",
    "trigger_keywords": [
      "suspend",
      "ban",
      "block",
      "abuse",
      "fraud",
      "spam",
      "violat"
    ],
    "triggers": {
      "labels_any_of": [
        "moderation",
        "abuse",
        "fraud"
      ],
      "title_pattern": "Suspend (user|account)|Account suspension|Fraudulent (account|activity)",
      "body_patterns": [
        "(suspend|ban|block|abuse|fraud|spam|violat)"
      ]
    },
    "steps": [
      {
        "tool": "humandesign.user.lookup",
        "slots": {
          "id": "$slots.user_id"
        },
        "side_effects": "none"
      },
      {
        "tool": "github.comment",
        "slots": {
          "body": "**Supervisor — pre-suspension verification**\n\nUser `$slots.user_id` found:\n- Email: $s1.email\n- Tier: $s1.tier\n- Status: $s1.status\n- Created: $s1.created_at\n\nProposed action: **suspend** with reason: \"$slots.reason\"\n\n⚠️ This action requires CODEOWNER approval. React ✅ to this comment to authorize.\nOnce approved, the supervisor will call `$slots.affected_app.user.suspend`.\n\n_Run ID: $RUN_ID_\n"
        },
        "side_effects": "none"
      },
      {
        "tool": "humandesign.user.suspend",
        "slots": {
          "id": "$slots.user_id",
          "reason": "$slots.reason"
        },
        "side_effects": "none"
      },
      {
        "tool": "github.addLabel",
        "slots": {
          "labels": [
            "status:done",
            "moderation:suspended"
          ]
        },
        "side_effects": "none"
      }
    ]
  },
  {
    "id": "ux-regression-triage",
    "tier": "yellow",
    "description": "",
    "trigger_keywords": [
      "accessibility",
      "bug",
      "regression",
      "triage"
    ],
    "triggers": {
      "labels_any_of": [
        "ux",
        "accessibility",
        "bug"
      ],
      "title_pattern": "^(\\[P[0-3]\\]\\[UX\\]|ux|bug)",
      "body_patterns": [
        "(?is)(repro|steps|expected|actual|viewport|mobile|a11y|accessibility)"
      ]
    },
    "steps": [
      {
        "tool": "github.comment",
        "slots": {
          "issue": "$issue.number",
          "body": "Supervisor triage plan for UX regression.\n- Confirm reproducibility (device + viewport)\n- Capture expected vs actual behavior\n- Propose minimal-risk fix path\n- Escalate P0/P1 for immediate assignment\n"
        },
        "side_effects": "none"
      }
    ]
  },
  {
    "id": "worker-health-degraded",
    "tier": "green",
    "description": "",
    "trigger_keywords": [
      "health",
      "degraded",
      "down",
      "503",
      "502",
      "timeout",
      "unreachable",
      "synthetic monitor"
    ],
    "triggers": {
      "labels_any_of": [
        "incident",
        "monitoring",
        "source:synthetic-monitor"
      ],
      "title_pattern": "Worker (health|degraded|down|503|502)|Synthetic monitor (fail|alert)|/health (returning|returning 5)",
      "body_patterns": [
        "(/health.*5[0-9]{2}|synthetic.*monitor.*fail|worker.*unreachable)"
      ]
    },
    "steps": [
      {
        "tool": "factory-admin.observability.summary",
        "slots": {},
        "side_effects": "none"
      },
      {
        "tool": "github.comment",
        "slots": {
          "body": "**Supervisor — worker health degradation triage**\n\nAffected worker: `$slots.affected_worker` (HTTP $slots.error_code)\nObservability summary: $s1.summary\n\n**Immediate checks (human):**\n1. `curl -I https://$slots.affected_worker.adrper79.workers.dev/health` — confirm current status\n2. Check Cloudflare dashboard for the worker at https://dash.cloudflare.com\n3. Check Sentry project for `$slots.affected_worker` for recent error spike\n4. If 502/503: check if a recent deployment is the cause via `wrangler rollback`\n\n**Rollback command (if deployment-related):**\n```\ncd apps/$slots.affected_worker && wrangler rollback\n```\n\n**Escalation:** If the worker is still degraded after 15 min, page on-call via Pushover.\n\nThe supervisor cannot invoke `wrangler rollback` (FRIDGE rule 8 — irreversible infra action). A CODEOWNER must execute this runbook.\n\n_Run ID: $RUN_ID_\n"
        },
        "side_effects": "none"
      },
      {
        "tool": "github.addLabel",
        "slots": {
          "labels": [
            "status:triaged",
            "incident",
            "supervisor:human-action-required"
          ]
        },
        "side_effects": "none"
      }
    ]
  },
  {
    "id": "wrangler-config-drift-fix",
    "tier": "yellow",
    "description": "",
    "trigger_keywords": [
      "bug",
      "wrangler",
      "config",
      "drift",
      "fix"
    ],
    "triggers": {
      "labels_any_of": [
        "bug"
      ],
      "title_pattern": "(wrangler|binding|Hyperdrive)",
      "body_patterns": [
        "(wrangler\\.jsonc|binding|hyperdrive|kv|r2|d1|durable_object)"
      ]
    },
    "steps": [
      {
        "tool": "github.readFile",
        "slots": {
          "repo": "$slots.app_name",
          "path": "wrangler.jsonc"
        },
        "side_effects": "none"
      },
      {
        "tool": "cloudflare.listWorkers",
        "slots": {
          "filter_binding_kind": "$slots.binding_kind",
          "filter_binding_id": "$slots.binding_id"
        },
        "side_effects": "none"
      },
      {
        "tool": "factory_admin.worker.status",
        "slots": {
          "worker": "$slots.worker_name"
        },
        "side_effects": "none"
      },
      {
        "tool": "github.openPR",
        "slots": {
          "repo": "$slots.app_name",
          "branch": "supervisor/wrangler-drift-$slots.worker_name",
          "title": "fix(wrangler): correct $slots.binding_kind binding for $slots.worker_name",
          "body": "Automated fix: wrangler.jsonc referenced a stale $slots.binding_kind binding. Updated to the resolved ID from cloudflare.listWorkers (see $s2). Current file state captured in $s1.",
          "files": [
            {
              "path": "wrangler.jsonc",
              "from_step": "s1",
              "patch_kind": "update_binding",
              "binding_kind": "$slots.binding_kind",
              "new_binding_id": "$s2.resolved_id"
            }
          ]
        },
        "side_effects": "none"
      }
    ]
  }
];
