#!/usr/bin/env node
// @node-runtime — Capability registry compiler
//
// Reads capabilities/{primitives,recipes,concepts,rules}/*.json and emits:
//   1. capabilities/dist/catalog.json — machine-readable bundle
//   2. apps/admin-studio/src/lib/capability-data.generated.ts — typed bundle
//
// Output is deterministic: keys are sorted, arrays are stable-sorted, and
// generatedAt is derived from the latest git mtime of any registry file
// (falls back to the file's mtime when not in a git checkout).
//
// CI also runs `validate.mjs && compile.mjs && git diff --exit-code` to
// guarantee the committed dist artifacts match HEAD.

import { execSync } from 'child_process';
import { readdirSync, readFileSync, writeFileSync, mkdirSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(__dirname, '../..');
const REGISTRY = join(REPO_ROOT, 'capabilities');
const DIST = join(REGISTRY, 'dist');
const TS_OUT = join(REPO_ROOT, 'apps/admin-studio/src/lib/capability-data.generated.ts');

function loadDir(dir) {
  if (!existsSync(dir)) return [];
  return readdirSync(dir)
    .filter((f) => f.endsWith('.json'))
    .sort()
    .map((f) => JSON.parse(readFileSync(join(dir, f), 'utf8')));
}

function deepSort(value) {
  if (Array.isArray(value)) return value.map(deepSort);
  if (value && typeof value === 'object') {
    const out = {};
    for (const key of Object.keys(value).sort()) {
      out[key] = deepSort(value[key]);
    }
    return out;
  }
  return value;
}

function deterministicTimestamp() {
  try {
    const output = execSync('git log -1 --format=%cI -- capabilities/concepts capabilities/primitives capabilities/recipes capabilities/rules', {
      cwd: REPO_ROOT,
      encoding: 'utf8',
      stdio: ['pipe', 'pipe', 'ignore'],
    }).trim();
    if (output) return new Date(output).toISOString();
  } catch {
    // Not in a git checkout, or no commits yet — fall through.
  }
  return '2026-05-23T00:00:00.000Z';
}

function buildCatalog() {
  const primitives = loadDir(join(REGISTRY, 'primitives'));
  const recipes = loadDir(join(REGISTRY, 'recipes'));
  const concepts = loadDir(join(REGISTRY, 'concepts'));
  const rules = loadDir(join(REGISTRY, 'rules'));

  // Merge all rule bundles into one canonical bundle ordered by rule id.
  const allRules = rules
    .flatMap((bundle) => bundle.rules ?? [])
    .sort((a, b) => a.id.localeCompare(b.id));

  const generatedAt = deterministicTimestamp();

  return {
    schemaVersion: '1.0.0',
    kind: 'capability-catalog',
    generatedAt,
    summary: {
      conceptCount: concepts.length,
      primitiveCount: primitives.length,
      recipeCount: recipes.length,
      ruleFileCount: rules.length,
    },
    concepts: concepts
      .map((c) => deepSort(c))
      .sort((a, b) => a.id.localeCompare(b.id)),
    recipes: recipes
      .map((r) => deepSort(r))
      .sort((a, b) => a.id.localeCompare(b.id)),
    primitives: primitives
      .map((p) => deepSort(p))
      .sort((a, b) => a.id.localeCompare(b.id)),
    ruleBundle: {
      rules: allRules,
    },
  };
}

function emitTypeScript(catalog) {
  // We emit the catalog as a single typed module re-exporting the JSON shape
  // so admin-studio's existing imports keep their type information without
  // requiring tsup JSON-import support.
  const banner =
    `// DO NOT EDIT — generated by scripts/capabilities/compile.mjs from capabilities/*.json.\n` +
    `// Run \`node scripts/capabilities/compile.mjs\` to regenerate after changing the registry.\n`;

  const body = `import type {
  CapabilityCatalogBundle,
  CapabilityConcept,
  CapabilityPrimitiveDescriptor,
  CapabilityRecipeDetail,
  CapabilityRuleBundle,
} from './capability-types.js';

const catalog = ${JSON.stringify(catalog, null, 2)} as const;

export const compiledCapabilityCatalog: CapabilityCatalogBundle = catalog as unknown as CapabilityCatalogBundle;
export const compiledCapabilityConcepts: readonly CapabilityConcept[] = catalog.concepts as unknown as readonly CapabilityConcept[];
export const compiledCapabilityRecipes: readonly CapabilityRecipeDetail[] = catalog.recipes as unknown as readonly CapabilityRecipeDetail[];
export const compiledCapabilityPrimitives: readonly CapabilityPrimitiveDescriptor[] = catalog.primitives as unknown as readonly CapabilityPrimitiveDescriptor[];
export const compiledCapabilityRuleBundle: CapabilityRuleBundle = catalog.ruleBundle as unknown as CapabilityRuleBundle;
`;

  return banner + body;
}

function main() {
  console.log('🛠  Compiling capability registry...');
  const catalog = buildCatalog();

  mkdirSync(DIST, { recursive: true });
  writeFileSync(join(DIST, 'catalog.json'), JSON.stringify(catalog, null, 2) + '\n', 'utf8');
  console.log(`   📄 capabilities/dist/catalog.json`);

  const ts = emitTypeScript(catalog);
  writeFileSync(TS_OUT, ts, 'utf8');
  console.log(`   📄 apps/admin-studio/src/lib/capability-data.generated.ts`);

  console.log('\n✅ Compiled.');
}

main();
