// AUTO-GENERATED by scripts/generate-supervisor-capabilities.mjs
// DO NOT EDIT DIRECTLY — edit docs/capabilities/*.yml instead,
// then run: node scripts/generate-supervisor-capabilities.mjs
//
// Generated: 2026-06-22T17:36:16.303Z
// Source files: coh.yml, factory-admin.yml, humandesign.yml, videoking.yml, webhook-fanout.yml, xico-city.yml

export type SideEffect = 'none' | 'read-external' | 'write-app' | 'write-external';
export type SupervisorAccess = 'green' | 'yellow' | 'red' | 'denied';

export interface RouteCapability {
  path: string;
  method: string;
  handler_class: string;
  side_effects: SideEffect;
  supervisor_access: SupervisorAccess;
  reversibility?: string;
  requires_codeowner_oob?: boolean;
  params_schema?: Record<string, unknown>;
  body_schema?: Record<string, unknown>;
}

export interface AppCapabilities {
  app: string;
  name: string;
  repo: string;
  base_url: string;
  product_tier: string;
  tiers_allowed: SupervisorAccess[];
  capabilities: RouteCapability[];
  capabilities_exposed: string[];
  capabilities_required: string[];
  side_effects_summary: Record<string, string[]>;
}

export const GENERATED_CAPABILITIES: AppCapabilities[] = [
  {
    "app": "coh",
    "name": "cypher-of-healing",
    "repo": "Latimer-Woods-Tech/coh",
    "base_url": "https://api.cypherofhealing.com",
    "product_tier": "revenue",
    "tiers_allowed": [
      "green",
      "yellow",
      "red"
    ],
    "capabilities": [
      {
        "path": "/health",
        "method": "GET",
        "handler_class": "read-internal",
        "side_effects": "none",
        "supervisor_access": "green"
      },
      {
        "path": "/api/admin/health",
        "method": "GET",
        "handler_class": "read-internal",
        "side_effects": "none",
        "supervisor_access": "green"
      },
      {
        "path": "/api/admin/metrics",
        "method": "GET",
        "handler_class": "read-internal",
        "side_effects": "none",
        "supervisor_access": "green",
        "params_schema": {
          "window": {
            "type": "enum",
            "values": [
              "1h",
              "6h",
              "24h",
              "7d"
            ],
            "optional": true
          }
        }
      },
      {
        "path": "/api/admin/events",
        "method": "GET",
        "handler_class": "read-internal",
        "side_effects": "none",
        "supervisor_access": "green",
        "params_schema": {
          "severity": {
            "type": "enum",
            "values": [
              "error",
              "warn",
              "info"
            ],
            "optional": true
          },
          "limit": {
            "type": "integer",
            "min": 1,
            "max": 100,
            "optional": true
          }
        }
      },
      {
        "path": "/auth/login",
        "method": "POST",
        "handler_class": "auth-internal",
        "side_effects": "none",
        "supervisor_access": "denied"
      },
      {
        "path": "/auth/refresh",
        "method": "POST",
        "handler_class": "auth-internal",
        "side_effects": "none",
        "supervisor_access": "denied"
      },
      {
        "path": "/api/admin/bookings",
        "method": "GET",
        "handler_class": "read-internal",
        "side_effects": "none",
        "supervisor_access": "green",
        "params_schema": {
          "page": {
            "type": "integer",
            "min": 1,
            "optional": true
          },
          "limit": {
            "type": "integer",
            "min": 1,
            "max": 100,
            "optional": true
          },
          "status": {
            "type": "enum",
            "values": [
              "pending",
              "confirmed",
              "completed",
              "cancelled"
            ],
            "optional": true
          }
        }
      },
      {
        "path": "/api/admin/bookings/:id",
        "method": "GET",
        "handler_class": "read-internal",
        "side_effects": "none",
        "supervisor_access": "green"
      },
      {
        "path": "/api/admin/bookings/:id/cancel",
        "method": "POST",
        "handler_class": "mutate-internal",
        "side_effects": "write-app",
        "supervisor_access": "yellow",
        "reversibility": "reversible-with-effort",
        "requires_codeowner_oob": true,
        "body_schema": {
          "reason": {
            "type": "string",
            "validator": "^[\\w\\s,\\.\\-]{10,200}$"
          }
        }
      },
      {
        "path": "/api/admin/practitioners",
        "method": "GET",
        "handler_class": "read-internal",
        "side_effects": "none",
        "supervisor_access": "green",
        "params_schema": {
          "page": {
            "type": "integer",
            "min": 1,
            "optional": true
          },
          "limit": {
            "type": "integer",
            "min": 1,
            "max": 100,
            "optional": true
          },
          "status": {
            "type": "enum",
            "values": [
              "active",
              "pending",
              "suspended"
            ],
            "optional": true
          }
        }
      },
      {
        "path": "/api/admin/practitioners/:id",
        "method": "GET",
        "handler_class": "read-internal",
        "side_effects": "none",
        "supervisor_access": "green"
      },
      {
        "path": "/api/admin/practitioners/:id/suspend",
        "method": "POST",
        "handler_class": "mutate-internal",
        "side_effects": "write-app",
        "supervisor_access": "yellow",
        "reversibility": "reversible-with-effort",
        "requires_codeowner_oob": true,
        "body_schema": {
          "reason": {
            "type": "string",
            "validator": "^[\\w\\s,\\.\\-]{10,200}$"
          }
        }
      },
      {
        "path": "/api/admin/subscriptions",
        "method": "GET",
        "handler_class": "read-internal",
        "side_effects": "none",
        "supervisor_access": "green",
        "params_schema": {
          "page": {
            "type": "integer",
            "min": 1,
            "optional": true
          },
          "limit": {
            "type": "integer",
            "min": 1,
            "max": 100,
            "optional": true
          },
          "status": {
            "type": "enum",
            "values": [
              "active",
              "cancelled",
              "past_due",
              "trialing"
            ],
            "optional": true
          }
        }
      },
      {
        "path": "/api/admin/subscriptions/:id/cancel",
        "method": "POST",
        "handler_class": "mutate-internal",
        "side_effects": "write-external",
        "supervisor_access": "red",
        "reversibility": "reversible-with-effort",
        "requires_codeowner_oob": true,
        "body_schema": {
          "reason": {
            "type": "string",
            "validator": "^[\\w\\s,\\.\\-]{10,200}$"
          },
          "at_period_end": {
            "type": "boolean",
            "optional": true
          }
        }
      },
      {
        "path": "/api/stripe/webhook",
        "method": "POST",
        "handler_class": "webhook-external",
        "side_effects": "write-external",
        "supervisor_access": "denied"
      },
      {
        "path": "/webhooks/stripe",
        "method": "POST",
        "handler_class": "webhook-external",
        "side_effects": "write-external",
        "supervisor_access": "denied"
      }
    ],
    "capabilities_exposed": [
      "booking-management",
      "practitioner-management",
      "subscription-management"
    ],
    "capabilities_required": [
      "@latimer-woods-tech/auth@^0.2.0",
      "@latimer-woods-tech/neon@^0.2.0",
      "@latimer-woods-tech/stripe@^0.2.0",
      "@latimer-woods-tech/llm@^0.3.0"
    ],
    "side_effects_summary": {
      "read_external": [
        "sentry-api",
        "posthog"
      ],
      "write_external": [
        "stripe",
        "resend",
        "anthropic"
      ],
      "write_app": [
        "neon:coh"
      ]
    }
  },
  {
    "app": "admin-studio-production",
    "name": "factory-admin-studio",
    "repo": "Latimer-Woods-Tech/factory",
    "base_url": "https://api.apunlimited.com",
    "product_tier": "internal",
    "tiers_allowed": [
      "green"
    ],
    "capabilities": [
      {
        "path": "/health",
        "method": "GET",
        "handler_class": "read-internal",
        "side_effects": "none",
        "supervisor_access": "green"
      },
      {
        "path": "/v1/health",
        "method": "GET",
        "handler_class": "read-internal",
        "side_effects": "none",
        "supervisor_access": "green"
      },
      {
        "path": "/v1/blocking",
        "method": "GET",
        "handler_class": "read-internal",
        "side_effects": "none",
        "supervisor_access": "green",
        "params_schema": {
          "app": {
            "type": "string",
            "validator": "^[a-z\\-]{3,40}$",
            "optional": true
          },
          "limit": {
            "type": "integer",
            "min": 1,
            "max": 100,
            "optional": true
          }
        }
      },
      {
        "path": "/v1/command-center/runs",
        "method": "GET",
        "handler_class": "read-internal",
        "side_effects": "none",
        "supervisor_access": "green",
        "params_schema": {
          "limit": {
            "type": "integer",
            "min": 1,
            "max": 100,
            "optional": true
          },
          "status": {
            "type": "enum",
            "values": [
              "running",
              "done",
              "failed",
              "cancelled"
            ],
            "optional": true
          }
        }
      },
      {
        "path": "/v1/command-center/gates",
        "method": "GET",
        "handler_class": "read-internal",
        "side_effects": "none",
        "supervisor_access": "green",
        "params_schema": {
          "run_id": {
            "type": "string",
            "optional": true
          },
          "limit": {
            "type": "integer",
            "min": 1,
            "max": 100,
            "optional": true
          }
        }
      },
      {
        "path": "/v1/command-center/artifacts",
        "method": "GET",
        "handler_class": "read-internal",
        "side_effects": "none",
        "supervisor_access": "green",
        "params_schema": {
          "run_id": {
            "type": "string",
            "optional": true
          },
          "limit": {
            "type": "integer",
            "min": 1,
            "max": 100,
            "optional": true
          }
        }
      },
      {
        "path": "/v1/audit",
        "method": "GET",
        "handler_class": "read-internal",
        "side_effects": "none",
        "supervisor_access": "green",
        "params_schema": {
          "actor": {
            "type": "string",
            "optional": true
          },
          "action": {
            "type": "string",
            "optional": true
          },
          "limit": {
            "type": "integer",
            "min": 1,
            "max": 100,
            "optional": true
          }
        }
      },
      {
        "path": "/v1/audit",
        "method": "POST",
        "handler_class": "mutate-internal",
        "side_effects": "write-app",
        "supervisor_access": "denied"
      },
      {
        "path": "/v1/events",
        "method": "POST",
        "handler_class": "mutate-internal",
        "side_effects": "write-app",
        "supervisor_access": "denied"
      }
    ],
    "capabilities_exposed": [
      "command-center-visibility",
      "audit-log-read",
      "gate-status"
    ],
    "capabilities_required": [
      "@latimer-woods-tech/auth@^0.2.0",
      "@latimer-woods-tech/neon@^0.2.0",
      "@latimer-woods-tech/monitoring@^0.2.0"
    ],
    "side_effects_summary": {
      "read_external": [
        "sentry-api"
      ],
      "write_external": [],
      "write_app": [
        "neon:factory-main"
      ]
    }
  },
  {
    "app": "humandesign",
    "name": "HumanDesign / selfprime",
    "repo": "Latimer-Woods-Tech/HumanDesign",
    "base_url": "https://api.selfprime.net",
    "product_tier": "revenue",
    "tiers_allowed": [
      "green",
      "yellow",
      "red"
    ],
    "capabilities": [
      {
        "path": "/auth/login",
        "method": "POST",
        "handler_class": "auth-internal",
        "side_effects": "none",
        "supervisor_access": "denied"
      },
      {
        "path": "/auth/refresh",
        "method": "POST",
        "handler_class": "auth-internal",
        "side_effects": "none",
        "supervisor_access": "denied"
      },
      {
        "path": "/api/practitioners",
        "method": "GET",
        "handler_class": "read-internal",
        "side_effects": "none",
        "supervisor_access": "green",
        "params_schema": {
          "page": {
            "type": "integer",
            "min": 1,
            "optional": true
          },
          "limit": {
            "type": "integer",
            "min": 1,
            "max": 100,
            "optional": true
          },
          "status": {
            "type": "enum",
            "values": [
              "active",
              "pending",
              "suspended"
            ],
            "optional": true
          }
        }
      },
      {
        "path": "/api/practitioners/:id",
        "method": "GET",
        "handler_class": "read-internal",
        "side_effects": "none",
        "supervisor_access": "green"
      },
      {
        "path": "/api/admin/health",
        "method": "GET",
        "handler_class": "read-internal",
        "side_effects": "none",
        "supervisor_access": "green"
      },
      {
        "path": "/api/admin/metrics",
        "method": "GET",
        "handler_class": "read-internal",
        "side_effects": "none",
        "supervisor_access": "green",
        "params_schema": {
          "window": {
            "type": "enum",
            "values": [
              "1h",
              "6h",
              "24h",
              "7d"
            ],
            "optional": true
          }
        }
      },
      {
        "path": "/api/admin/events",
        "method": "GET",
        "handler_class": "read-internal",
        "side_effects": "none",
        "supervisor_access": "green",
        "params_schema": {
          "severity": {
            "type": "enum",
            "values": [
              "error",
              "warn",
              "info"
            ],
            "optional": true
          },
          "limit": {
            "type": "integer",
            "min": 1,
            "max": 100,
            "optional": true
          },
          "user_id": {
            "type": "string",
            "validator": "^[a-zA-Z0-9\\-]{1,64}$",
            "optional": true
          }
        }
      },
      {
        "path": "/api/admin/users",
        "method": "GET",
        "handler_class": "read-internal",
        "side_effects": "none",
        "supervisor_access": "green",
        "params_schema": {
          "page": {
            "type": "integer",
            "min": 1,
            "optional": true
          },
          "limit": {
            "type": "integer",
            "min": 1,
            "max": 100,
            "optional": true
          },
          "tier": {
            "type": "enum",
            "values": [
              "individual",
              "practitioner",
              "agency"
            ],
            "optional": true
          },
          "status": {
            "type": "enum",
            "values": [
              "active",
              "suspended",
              "pending"
            ],
            "optional": true
          }
        }
      },
      {
        "path": "/api/admin/users/:id",
        "method": "GET",
        "handler_class": "read-internal",
        "side_effects": "none",
        "supervisor_access": "green"
      },
      {
        "path": "/api/admin/users/:id/suspend",
        "method": "POST",
        "handler_class": "mutate-internal",
        "side_effects": "write-app",
        "supervisor_access": "yellow",
        "reversibility": "reversible-with-effort",
        "requires_codeowner_oob": true,
        "body_schema": {
          "reason": {
            "type": "string",
            "validator": "^[\\w\\s,\\.\\-]{10,200}$"
          }
        }
      },
      {
        "path": "/api/admin/users/:id/reinstate",
        "method": "POST",
        "handler_class": "mutate-internal",
        "side_effects": "write-app",
        "supervisor_access": "yellow",
        "reversibility": "idempotent",
        "requires_codeowner_oob": true,
        "body_schema": {
          "reason": {
            "type": "string",
            "validator": "^[\\w\\s,\\.\\-]{10,200}$"
          }
        }
      },
      {
        "path": "/api/admin/users/:id/tier",
        "method": "POST",
        "handler_class": "mutate-internal",
        "side_effects": "write-external",
        "supervisor_access": "red",
        "reversibility": "reversible-with-effort",
        "requires_codeowner_oob": true,
        "body_schema": {
          "new_tier": {
            "type": "enum",
            "values": [
              "individual",
              "practitioner",
              "agency"
            ]
          }
        }
      },
      {
        "path": "/api/admin/synthesis",
        "method": "POST",
        "handler_class": "mutate-internal",
        "side_effects": "write-app",
        "supervisor_access": "yellow",
        "reversibility": "idempotent",
        "body_schema": {
          "user_id": {
            "type": "string",
            "validator": "^[a-zA-Z0-9\\-]{1,64}$"
          },
          "chart_type": {
            "type": "enum",
            "values": [
              "natal",
              "transit",
              "synastry"
            ]
          },
          "force_refresh": {
            "type": "boolean",
            "optional": true
          }
        }
      },
      {
        "path": "/api/stripe/webhook",
        "method": "POST",
        "handler_class": "webhook-external",
        "side_effects": "write-external",
        "supervisor_access": "denied"
      }
    ],
    "capabilities_exposed": [
      "synthesize-energy-blueprint",
      "generate-practitioner-pdf",
      "user-management",
      "practitioner-directory"
    ],
    "capabilities_required": [
      "@latimer-woods-tech/llm@^0.3.0",
      "@latimer-woods-tech/stripe@^0.2.0",
      "@latimer-woods-tech/auth@^0.2.0"
    ],
    "side_effects_summary": {
      "read_external": [
        "sentry-api",
        "posthog"
      ],
      "write_external": [
        "stripe",
        "anthropic",
        "resend"
      ],
      "write_app": [
        "neon:divine-grass-42421088"
      ]
    }
  },
  {
    "app": "capricast",
    "name": "capricast",
    "repo": "Latimer-Woods-Tech/capricast",
    "base_url": "https://api.capricast.com",
    "product_tier": "revenue",
    "tiers_allowed": [
      "green",
      "yellow",
      "red"
    ],
    "capabilities": [
      {
        "path": "/api/admin/health",
        "method": "GET",
        "handler_class": "read-internal",
        "side_effects": "none",
        "supervisor_access": "green"
      },
      {
        "path": "/api/admin/metrics",
        "method": "GET",
        "handler_class": "read-internal",
        "side_effects": "none",
        "supervisor_access": "green",
        "params_schema": {
          "window": {
            "type": "enum",
            "values": [
              "1h",
              "6h",
              "24h",
              "7d"
            ],
            "optional": true
          }
        }
      },
      {
        "path": "/api/admin/events",
        "method": "GET",
        "handler_class": "read-internal",
        "side_effects": "none",
        "supervisor_access": "green",
        "params_schema": {
          "severity": {
            "type": "enum",
            "values": [
              "error",
              "warn",
              "info"
            ],
            "optional": true
          },
          "limit": {
            "type": "integer",
            "min": 1,
            "max": 100,
            "optional": true
          }
        }
      },
      {
        "path": "/api/admin/creators",
        "method": "GET",
        "handler_class": "read-internal",
        "side_effects": "none",
        "supervisor_access": "green",
        "params_schema": {
          "page": {
            "type": "integer",
            "min": 1,
            "optional": true
          },
          "limit": {
            "type": "integer",
            "min": 1,
            "max": 100,
            "optional": true
          },
          "status": {
            "type": "enum",
            "values": [
              "pending",
              "active",
              "suspended",
              "onboarding"
            ],
            "optional": true
          }
        }
      },
      {
        "path": "/api/admin/creators/:id",
        "method": "GET",
        "handler_class": "read-internal",
        "side_effects": "none",
        "supervisor_access": "green"
      },
      {
        "path": "/api/admin/creators/:id/verify-stripe",
        "method": "POST",
        "handler_class": "mutate-internal",
        "side_effects": "write-external",
        "supervisor_access": "yellow",
        "reversibility": "idempotent",
        "requires_codeowner_oob": false
      },
      {
        "path": "/api/admin/creators/:id/mark-ready-for-payout",
        "method": "POST",
        "handler_class": "mutate-internal",
        "side_effects": "write-app",
        "supervisor_access": "yellow",
        "reversibility": "reversible-with-effort",
        "requires_codeowner_oob": true
      },
      {
        "path": "/api/admin/payouts/batches",
        "method": "GET",
        "handler_class": "read-internal",
        "side_effects": "none",
        "supervisor_access": "green",
        "params_schema": {
          "limit": {
            "type": "integer",
            "min": 1,
            "max": 50,
            "optional": true
          }
        }
      },
      {
        "path": "/api/admin/payouts",
        "method": "POST",
        "handler_class": "mutate-internal",
        "side_effects": "write-external",
        "supervisor_access": "red",
        "reversibility": "reversible-with-effort",
        "requires_codeowner_oob": true,
        "body_schema": {
          "creator_id": {
            "type": "string",
            "validator": "^[a-zA-Z0-9\\-]{1,64}$"
          },
          "amount_cents": {
            "type": "integer",
            "min": 100
          },
          "currency": {
            "type": "enum",
            "values": [
              "usd",
              "eur",
              "gbp"
            ],
            "optional": true
          }
        }
      },
      {
        "path": "/api/admin/videos",
        "method": "GET",
        "handler_class": "read-internal",
        "side_effects": "none",
        "supervisor_access": "green",
        "params_schema": {
          "page": {
            "type": "integer",
            "min": 1,
            "optional": true
          },
          "limit": {
            "type": "integer",
            "min": 1,
            "max": 100,
            "optional": true
          },
          "status": {
            "type": "enum",
            "values": [
              "pending",
              "processing",
              "published",
              "failed"
            ],
            "optional": true
          }
        }
      },
      {
        "path": "/api/admin/videos/import",
        "method": "POST",
        "handler_class": "mutate-internal",
        "side_effects": "write-app",
        "supervisor_access": "yellow",
        "reversibility": "idempotent",
        "body_schema": {
          "stream_video_id": {
            "type": "string",
            "validator": "^[a-f0-9\\-]{32,64}$"
          },
          "title": {
            "type": "string",
            "validator": "^.{1,200}$"
          },
          "creator_id": {
            "type": "string",
            "validator": "^[a-zA-Z0-9\\-]{1,64}$"
          }
        }
      },
      {
        "path": "/api/creator/onboarding",
        "method": "GET",
        "handler_class": "read-internal",
        "side_effects": "none",
        "supervisor_access": "green"
      },
      {
        "path": "/api/stripe/webhook",
        "method": "POST",
        "handler_class": "webhook-external",
        "side_effects": "write-external",
        "supervisor_access": "denied"
      },
      {
        "path": "/webhooks/stripe-connect",
        "method": "POST",
        "handler_class": "webhook-external",
        "side_effects": "write-external",
        "supervisor_access": "denied"
      },
      {
        "path": "/health",
        "method": "GET",
        "handler_class": "read-internal",
        "side_effects": "none",
        "supervisor_access": "green"
      }
    ],
    "capabilities_exposed": [
      "creator-management",
      "payout-processing",
      "video-import",
      "creator-onboarding"
    ],
    "capabilities_required": [
      "@latimer-woods-tech/stripe@^0.2.0",
      "@latimer-woods-tech/auth@^0.2.0",
      "@latimer-woods-tech/neon@^0.2.0"
    ],
    "side_effects_summary": {
      "read_external": [
        "sentry-api",
        "posthog",
        "cloudflare-stream"
      ],
      "write_external": [
        "stripe",
        "cloudflare-stream",
        "resend"
      ],
      "write_app": [
        "neon:72697ebbf0d44419850743679390acf1"
      ]
    }
  },
  {
    "app": "webhook-fanout",
    "name": "webhook-fanout",
    "repo": "Latimer-Woods-Tech/factory",
    "base_url": "https://webhooks.latwoodtech.work",
    "product_tier": "internal",
    "tiers_allowed": [
      "green"
    ],
    "capabilities": [
      {
        "path": "/health",
        "method": "GET",
        "handler_class": "read-internal",
        "side_effects": "none",
        "supervisor_access": "green"
      },
      {
        "path": "/stripe",
        "method": "POST",
        "handler_class": "webhook-external",
        "side_effects": "write-external",
        "supervisor_access": "denied"
      }
    ],
    "capabilities_exposed": [
      "stripe-webhook-fanout"
    ],
    "capabilities_required": [
      "@latimer-woods-tech/analytics@^0.2.0",
      "@latimer-woods-tech/email@^0.2.0"
    ],
    "side_effects_summary": {
      "read_external": [
        "stripe-hmac-verify"
      ],
      "write_external": [
        "posthog",
        "resend"
      ],
      "write_app": [
        "neon:factory-main",
        "kv:webhook-dedup"
      ]
    }
  },
  {
    "app": "xico-city",
    "name": "xico-city",
    "repo": "Latimer-Woods-Tech/xico-city",
    "base_url": "https://xicocity.com",
    "product_tier": "revenue",
    "tiers_allowed": [
      "green",
      "yellow"
    ],
    "capabilities": [
      {
        "path": "/health",
        "method": "GET",
        "handler_class": "read-internal",
        "side_effects": "none",
        "supervisor_access": "green"
      },
      {
        "path": "/api/admin/health",
        "method": "GET",
        "handler_class": "read-internal",
        "side_effects": "none",
        "supervisor_access": "green"
      },
      {
        "path": "/api/admin/metrics",
        "method": "GET",
        "handler_class": "read-internal",
        "side_effects": "none",
        "supervisor_access": "green",
        "params_schema": {
          "window": {
            "type": "enum",
            "values": [
              "1h",
              "6h",
              "24h",
              "7d"
            ],
            "optional": true
          }
        }
      },
      {
        "path": "/api/admin/events",
        "method": "GET",
        "handler_class": "read-internal",
        "side_effects": "none",
        "supervisor_access": "green",
        "params_schema": {
          "severity": {
            "type": "enum",
            "values": [
              "error",
              "warn",
              "info"
            ],
            "optional": true
          },
          "limit": {
            "type": "integer",
            "min": 1,
            "max": 100,
            "optional": true
          }
        }
      },
      {
        "path": "/api/admin/users",
        "method": "GET",
        "handler_class": "read-internal",
        "side_effects": "none",
        "supervisor_access": "green",
        "params_schema": {
          "page": {
            "type": "integer",
            "min": 1,
            "optional": true
          },
          "limit": {
            "type": "integer",
            "min": 1,
            "max": 100,
            "optional": true
          },
          "role": {
            "type": "string",
            "validator": "^[a-z_]{3,40}$",
            "optional": true
          }
        }
      },
      {
        "path": "/api/admin/users/:id",
        "method": "GET",
        "handler_class": "read-internal",
        "side_effects": "none",
        "supervisor_access": "green"
      },
      {
        "path": "/api/admin/users/:id/suspend",
        "method": "POST",
        "handler_class": "mutate-internal",
        "side_effects": "write-app",
        "supervisor_access": "yellow",
        "reversibility": "reversible-with-effort",
        "requires_codeowner_oob": true,
        "body_schema": {
          "reason": {
            "type": "string",
            "validator": "^[\\w\\s,\\.\\-]{10,200}$"
          }
        }
      },
      {
        "path": "/api/admin/users/:id/reinstate",
        "method": "POST",
        "handler_class": "mutate-internal",
        "side_effects": "write-app",
        "supervisor_access": "yellow",
        "reversibility": "idempotent",
        "requires_codeowner_oob": true,
        "body_schema": {
          "reason": {
            "type": "string",
            "validator": "^[\\w\\s,\\.\\-]{10,200}$"
          }
        }
      },
      {
        "path": "/api/admin/content",
        "method": "GET",
        "handler_class": "read-internal",
        "side_effects": "none",
        "supervisor_access": "green",
        "params_schema": {
          "page": {
            "type": "integer",
            "min": 1,
            "optional": true
          },
          "limit": {
            "type": "integer",
            "min": 1,
            "max": 100,
            "optional": true
          },
          "status": {
            "type": "enum",
            "values": [
              "draft",
              "published",
              "archived"
            ],
            "optional": true
          }
        }
      },
      {
        "path": "/auth/login",
        "method": "POST",
        "handler_class": "auth-internal",
        "side_effects": "none",
        "supervisor_access": "denied"
      },
      {
        "path": "/auth/refresh",
        "method": "POST",
        "handler_class": "auth-internal",
        "side_effects": "none",
        "supervisor_access": "denied"
      },
      {
        "path": "/api/stripe/webhook",
        "method": "POST",
        "handler_class": "webhook-external",
        "side_effects": "write-external",
        "supervisor_access": "denied"
      }
    ],
    "capabilities_exposed": [
      "user-management",
      "artist-directory",
      "content-moderation"
    ],
    "capabilities_required": [
      "@latimer-woods-tech/auth@^0.2.0",
      "@latimer-woods-tech/neon@^0.2.0",
      "@latimer-woods-tech/stripe@^0.2.0"
    ],
    "side_effects_summary": {
      "read_external": [
        "sentry-api",
        "posthog"
      ],
      "write_external": [
        "stripe",
        "resend"
      ],
      "write_app": [
        "neon:xico-city"
      ]
    }
  }
];

export function getAppCapabilities(appId: string): AppCapabilities | undefined {
  return GENERATED_CAPABILITIES.find((a) => a.app === appId);
}

export function getCapability(
  appId: string,
  path: string,
  method?: string,
): RouteCapability | undefined {
  return getAppCapabilities(appId)?.capabilities.find(
    (c) => c.path === path && (method === undefined || c.method === method),
  );
}
