// AUTO-GENERATED by scripts/generate-supervisor-capabilities.mjs
// DO NOT EDIT DIRECTLY — edit docs/capabilities/*.yml instead,
// then run: node scripts/generate-supervisor-capabilities.mjs
//
// Generated: 2026-05-25T00:20:12.802Z
// Source files: factory-admin.yml, humandesign.yml, videoking.yml, webhook-fanout.yml, xico-city.yml

export interface Capability {
  id: string;
  desc?: string;
  route: string;
  side_effects: 'none' | 'read-external' | 'write-app' | 'write-external';
  required_scope: string;
  idempotency_key?: string;
  reversibility?: string;
  extra_guard?: string;
  params_schema?: Record<string, unknown>;
  body_schema?: Record<string, unknown>;
}

export interface AppCapabilities {
  app: string;
  repo: string;
  base_url: string;
  auth: string;
  supervisor_access: string;
  tiers_allowed: string[];
  capabilities: Capability[];
}

export const GENERATED_CAPABILITIES: AppCapabilities[] = [
  {
    "app": "factory-admin",
    "repo": "Latimer-Woods-Tech/factory",
    "base_url": "https://admin-studio.adrper79.workers.dev",
    "auth": "admin_jwt",
    "supervisor_access": "approved",
    "tiers_allowed": [
      "green",
      "yellow",
      "red"
    ],
    "capabilities": [
      {
        "id": "health.check",
        "desc": "Admin-studio liveness check.",
        "route": "GET /health",
        "side_effects": "none",
        "required_scope": "supervisor.readonly"
      },
      {
        "id": "deploys.list",
        "desc": "List recent Cloudflare Worker deployments across all apps.",
        "route": "GET /deploys",
        "params_schema": {
          "limit": {
            "type": "integer",
            "min": 1,
            "max": 50
          }
        },
        "side_effects": "none",
        "required_scope": "supervisor.readonly"
      },
      {
        "id": "deploys.trigger",
        "desc": "Dispatch a workflow_dispatch to re-deploy an app. Only for Green-tier deploys (docs-only). Red-tier deploys require human.",
        "route": "POST /deploys",
        "body_schema": {
          "app": {
            "type": "enum",
            "values": [
              "humandesign",
              "videoking",
              "xico-city",
              "factory-admin"
            ]
          },
          "ref": {
            "type": "string",
            "validator": "^[a-zA-Z0-9/_\\-\\.]{1,100}$"
          },
          "env": {
            "type": "enum",
            "values": [
              "staging"
            ]
          }
        },
        "idempotency_key": "app + ref + env",
        "side_effects": "write-external",
        "reversibility": "reversible-with-effort",
        "required_scope": "supervisor.mutator-deploy",
        "extra_guard": "requires_codeowner_approval"
      },
      {
        "id": "observability.summary",
        "desc": "Fetch cross-app Sentry error rates and synthetic monitor status.",
        "route": "GET /observability",
        "side_effects": "none",
        "required_scope": "supervisor.readonly"
      },
      {
        "id": "audit.list",
        "desc": "Fetch recent studio audit log entries.",
        "route": "GET /audit",
        "params_schema": {
          "limit": {
            "type": "integer",
            "min": 1,
            "max": 100
          },
          "app": {
            "type": "string",
            "validator": "^[a-z\\-]{3,40}$",
            "optional": true
          }
        },
        "side_effects": "none",
        "required_scope": "supervisor.readonly"
      },
      {
        "id": "catalog.list",
        "desc": "List function_catalog entries for an app.",
        "route": "GET /catalog",
        "params_schema": {
          "app": {
            "type": "string",
            "validator": "^[a-z\\-]{3,40}$"
          }
        },
        "side_effects": "none",
        "required_scope": "supervisor.readonly"
      },
      {
        "id": "timeline.list",
        "desc": "Fetch incident/audit timeline for correlation.",
        "route": "GET /timeline",
        "params_schema": {
          "limit": {
            "type": "integer",
            "min": 1,
            "max": 100
          }
        },
        "side_effects": "none",
        "required_scope": "supervisor.readonly"
      }
    ]
  },
  {
    "app": "humandesign",
    "repo": "Latimer-Woods-Tech/HumanDesign",
    "base_url": "https://api.selfprime.net",
    "auth": "admin_jwt",
    "supervisor_access": "approved",
    "tiers_allowed": [
      "green",
      "yellow"
    ],
    "capabilities": [
      {
        "id": "user.lookup",
        "desc": "Fetch a user's profile, tier, and account status by ID or email.",
        "route": "GET /admin/users/:id",
        "side_effects": "none",
        "required_scope": "supervisor.readonly"
      },
      {
        "id": "user.list",
        "desc": "Paginated list of users, optionally filtered by tier or status.",
        "route": "GET /admin/users",
        "params_schema": {
          "page": {
            "type": "integer",
            "min": 1
          },
          "limit": {
            "type": "integer",
            "min": 1,
            "max": 100
          },
          "tier": {
            "type": "enum",
            "values": [
              "individual",
              "practitioner",
              "agency"
            ],
            "optional": true
          },
          "status": {
            "type": "enum",
            "values": [
              "active",
              "suspended",
              "pending"
            ],
            "optional": true
          }
        },
        "side_effects": "none",
        "required_scope": "supervisor.readonly"
      },
      {
        "id": "user.suspend",
        "desc": "Suspend a user account. Reversible via user.reinstate.",
        "route": "POST /admin/users/:id/suspend",
        "body_schema": {
          "reason": {
            "type": "string",
            "validator": "^[\\w\\s,\\.\\-]{10,200}$"
          }
        },
        "idempotency_key": "user_id + 'suspend'",
        "side_effects": "write-app",
        "reversibility": "reversible-with-effort",
        "required_scope": "supervisor.mutator-user-suspend",
        "extra_guard": "requires_codeowner_approval"
      },
      {
        "id": "user.reinstate",
        "desc": "Reinstate a suspended user account.",
        "route": "POST /admin/users/:id/reinstate",
        "body_schema": {
          "reason": {
            "type": "string",
            "validator": "^[\\w\\s,\\.\\-]{10,200}$"
          }
        },
        "idempotency_key": "user_id + 'reinstate'",
        "side_effects": "write-app",
        "reversibility": "idempotent",
        "required_scope": "supervisor.mutator-user-reinstate",
        "extra_guard": "requires_codeowner_approval"
      },
      {
        "id": "subscription.tier_change",
        "desc": "Change a user's subscription tier. Writes to Stripe.",
        "route": "POST /admin/users/:id/tier",
        "body_schema": {
          "new_tier": {
            "type": "enum",
            "values": [
              "individual",
              "practitioner",
              "agency"
            ]
          }
        },
        "idempotency_key": "user_id + new_tier",
        "side_effects": "write-external",
        "reversibility": "reversible-with-effort",
        "required_scope": "supervisor.mutator-subscription-tier-change",
        "extra_guard": "requires_codeowner_approval"
      },
      {
        "id": "events.recent",
        "desc": "Fetch recent factory_events for a user.",
        "route": "GET /admin/events",
        "params_schema": {
          "user_id": {
            "type": "string",
            "validator": "^[a-zA-Z0-9\\-]{1,64}$",
            "optional": true
          },
          "limit": {
            "type": "integer",
            "min": 1,
            "max": 100
          }
        },
        "side_effects": "none",
        "required_scope": "supervisor.readonly"
      },
      {
        "id": "health.check",
        "desc": "Worker liveness check.",
        "route": "GET /health",
        "side_effects": "none",
        "required_scope": "supervisor.readonly"
      }
    ]
  },
  {
    "app": "videoking",
    "repo": "Latimer-Woods-Tech/capricast",
    "base_url": "https://api.capricast.com",
    "auth": "admin_jwt",
    "supervisor_access": "approved",
    "tiers_allowed": [
      "green",
      "yellow"
    ],
    "capabilities": [
      {
        "id": "creator.lookup",
        "desc": "Fetch a creator's profile, onboarding status, and Stripe connect state.",
        "route": "GET /api/admin/creators/:id",
        "side_effects": "none",
        "required_scope": "supervisor.readonly"
      },
      {
        "id": "creator.list",
        "desc": "Paginated list of creators with optional status filter.",
        "route": "GET /api/admin/creators",
        "params_schema": {
          "page": {
            "type": "integer",
            "min": 1
          },
          "limit": {
            "type": "integer",
            "min": 1,
            "max": 100
          },
          "status": {
            "type": "enum",
            "values": [
              "pending",
              "active",
              "suspended",
              "onboarding"
            ],
            "optional": true
          }
        },
        "side_effects": "none",
        "required_scope": "supervisor.readonly"
      },
      {
        "id": "creator.verify_stripe",
        "desc": "Trigger Stripe Connect verification for a creator. Idempotent — safe to re-run.",
        "route": "POST /api/admin/creators/:id/verify-stripe",
        "idempotency_key": "creator_id + 'verify-stripe'",
        "side_effects": "write-external",
        "reversibility": "idempotent",
        "required_scope": "supervisor.mutator-stripe-verify",
        "extra_guard": "requires_codeowner_approval"
      },
      {
        "id": "creator.mark_ready_for_payout",
        "desc": "Mark a creator as payout-eligible after manual KYC confirmation.",
        "route": "POST /api/admin/creators/:id/mark-ready-for-payout",
        "idempotency_key": "creator_id + 'mark-ready'",
        "side_effects": "write-app",
        "reversibility": "reversible-with-effort",
        "required_scope": "supervisor.mutator-creator-payout-ready",
        "extra_guard": "requires_codeowner_approval"
      },
      {
        "id": "payout.list_batches",
        "desc": "List payout batches with status.",
        "route": "GET /api/admin/payouts/batches",
        "params_schema": {
          "limit": {
            "type": "integer",
            "min": 1,
            "max": 50
          }
        },
        "side_effects": "none",
        "required_scope": "supervisor.readonly"
      },
      {
        "id": "onboarding.status",
        "desc": "Fetch a creator's onboarding funnel position.",
        "route": "GET /api/creator/onboarding",
        "side_effects": "none",
        "required_scope": "supervisor.readonly"
      },
      {
        "id": "health.check",
        "desc": "Worker liveness check.",
        "route": "GET /health",
        "side_effects": "none",
        "required_scope": "supervisor.readonly"
      }
    ]
  },
  {
    "app": "webhook-fanout",
    "base_url": "https://webhooks.latwoodtech.com",
    "auth": "none",
    "supervisor_access": "read-only",
    "tiers_allowed": [
      "green"
    ],
    "description": "Cloudflare Worker that ingests Stripe webhook events, verifies HMAC-SHA256 signatures, deduplicates via KV (7-day TTL), filters synthetic customers, and fans out to PostHog + factory_events (analytics) and Resend (lifecycle emails).\n",
    "routed_events": [
      {
        "stripe": "customer.created",
        "analytics_event": "stripe.customer.created",
        "lifecycle_email": "resend"
      },
      {
        "stripe": "customer.updated",
        "analytics_event": "stripe.customer.updated",
        "lifecycle_email": "resend"
      },
      {
        "stripe": "customer.subscription.created",
        "analytics_event": "stripe.customer.subscription.created",
        "lifecycle_email": "resend"
      },
      {
        "stripe": "customer.subscription.updated",
        "analytics_event": "stripe.customer.subscription.updated",
        "lifecycle_email": "resend"
      },
      {
        "stripe": "customer.subscription.deleted",
        "analytics_event": "stripe.customer.subscription.deleted",
        "lifecycle_email": "resend"
      },
      {
        "stripe": "customer.subscription.trial_will_end",
        "analytics_event": "stripe.customer.subscription.trial_will_end",
        "lifecycle_email": "resend"
      },
      {
        "stripe": "invoice.paid",
        "analytics_event": "stripe.invoice.paid",
        "lifecycle_email": "resend"
      },
      {
        "stripe": "invoice.payment_failed",
        "analytics_event": "stripe.invoice.payment_failed",
        "lifecycle_email": "resend"
      }
    ],
    "capabilities": [
      {
        "id": "health.check",
        "desc": "Worker liveness check.",
        "route": "GET /health",
        "side_effects": "none",
        "required_scope": "supervisor.readonly"
      },
      {
        "id": "stripe.webhook.receive",
        "desc": "Receive and process a Stripe webhook event. Verifies HMAC signature, deduplicates, filters synthetic customers, and fans out to PostHog, factory_events, and Resend.\n",
        "route": "POST /stripe",
        "side_effects": "write-external",
        "reversibility": "idempotent",
        "required_scope": "none",
        "notes": "Called exclusively by Stripe. Not for direct invocation by the Supervisor. Returns 200 immediately; fan-out continues in waitUntil().\n"
      }
    ]
  },
  {
    "app": "xico-city",
    "repo": "Latimer-Woods-Tech/xico-city",
    "base_url": "https://xico-city.adrper79.workers.dev",
    "auth": "admin_jwt",
    "supervisor_access": "approved",
    "tiers_allowed": [
      "green",
      "yellow"
    ],
    "capabilities": [
      {
        "id": "health.check",
        "desc": "Worker liveness check — /health and /ready.",
        "route": "GET /health",
        "side_effects": "none",
        "required_scope": "supervisor.readonly"
      },
      {
        "id": "compat.check",
        "desc": "Verify factory-core package compatibility contract.",
        "route": "GET /factory/compat",
        "side_effects": "none",
        "required_scope": "supervisor.readonly"
      },
      {
        "id": "user.me",
        "desc": "Fetch the authenticated user's profile.",
        "route": "GET /api/me",
        "side_effects": "none",
        "required_scope": "supervisor.readonly"
      },
      {
        "id": "admin.users.list",
        "desc": "List users (artist roles).",
        "route": "GET /admin/users",
        "params_schema": {
          "page": {
            "type": "integer",
            "min": 1
          },
          "limit": {
            "type": "integer",
            "min": 1,
            "max": 100
          },
          "role": {
            "type": "string",
            "validator": "^[a-z_]{3,40}$",
            "optional": true
          }
        },
        "side_effects": "none",
        "required_scope": "supervisor.readonly"
      },
      {
        "id": "admin.users.suspend",
        "desc": "Suspend an artist account.",
        "route": "POST /admin/users/:id/suspend",
        "body_schema": {
          "reason": {
            "type": "string",
            "validator": "^[\\w\\s,\\.\\-]{10,200}$"
          }
        },
        "idempotency_key": "user_id + 'suspend'",
        "side_effects": "write-app",
        "reversibility": "reversible-with-effort",
        "required_scope": "supervisor.mutator-user-suspend",
        "extra_guard": "requires_codeowner_approval"
      }
    ]
  }
];

export function getAppCapabilities(appId: string): AppCapabilities | undefined {
  return GENERATED_CAPABILITIES.find((a) => a.app === appId);
}

export function getCapability(appId: string, capId: string): Capability | undefined {
  return getAppCapabilities(appId)?.capabilities.find((c) => c.id === capId);
}
