name: Get Credentials for Login

on:
  workflow_dispatch:

jobs:
  get-creds:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Output credentials to workflow log
        run: |
          echo "FACTORY_USER=${{ secrets.FACTORY_USER }}" >> $GITHUB_OUTPUT
          echo "FACTORY_PW=${{ secrets.FACTORY_PW }}" >> $GITHUB_OUTPUT
        id: creds
      
      - name: Display for copy-paste
        run: |
          echo "Username: ${{ steps.creds.outputs.FACTORY_USER }}"
          echo "Password: ${{ steps.creds.outputs.FACTORY_PW }}"
